### ISSUE TITLE
Web UI feature request: responsive layout

### ISSUE THREAD

**Issue by aviflax** [jointakahe/takahe#102]
I’m using the app mostly on my phone and, well, it’s awkward.

I’m pretty rusty on how to do this kinda stuff, but if anyone wants to give me some tips I could give it a try…

**Comment by andrewgodwin** [comment]
This mostly just needs iteration - stick a desktop browser into the phone emulation mode, set the screen size pretty small, and then figure out what needs fixing and fix it one at a time.

Obviously, the goal to have support for the Mastodon Client APIs will help relieve the pressure here.

**Comment by jph7C1** [comment]
Oddly with edge dev tools on my work computer set to iPhone SE the page actually looks fine. On my actual iPhone 12 mini however it doesn’t scale right. I’ll look again with desktop safari when I get home but figured I should mention this here.

**Comment by andrewgodwin** [comment]
Yeah, there's some sort of scaling or meta tag I think is missing.

**Comment by jph7C1** [comment]
Ok I think I'm onto something. It happens in desktop Safari as well. Safari doesn't seem to like this media query on line 1194 of style.css:
`@media (max-width: 920px) or (display-mode: standalone) {`

From what I gather from reading MDN and some experimentation I think the right syntax would be:
`@media screen and (max-width: 920px), screen and (display-mode: standalone) {`

That works ok in the Safari dev tools but I haven't tested it in other browsers yet.

**Comment by jph7C1** [comment]
Ok after some more testing in Safari and Edge I don't think the `screen and` should be in there, simply replacing the `or` with a comma seems to make it work in Safari. The font scaling gets messy but it behaves the same way in Edge when emulating iOS devices. I think it has to do with pixels vs points on retina displays. It'll probably be a fairly deep dive to get this playing nice on iPhones if my hunch is correct.

In the mean time `@media (max-width: 920px), (display-mode: standalone) {` seems to at least not make things worse and gets Safari responding to the media queries.

**Comment by andrewgodwin** [comment]
Alright, I've put that change in for now. We can come back and iterate on this.

**Comment by jph7C1** [comment]
Sounds good. As a tip for other iPhone users with this change in place you can 'zoom out' the page a click or two and that seems to clean up the layout issues.

Tomorrow is the start of a long weekend for me and I'm hoping to spend some more time on this.

**Comment by andrewgodwin** [comment]
We've put a lot of work into this over the past couple of weeks and I believe we're in a better place now - if there's further issues with specific elements, please open tickets for them!

**Comment by aviflax** [comment]
I use my install mostly on my phone, and I can attest that the UX has greatly improved over recent weeks. Thank you all!
