### ISSUE TITLE
Add images to RSS feed

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#104]
There's now a user RSS feed at `/@handle/rss/`, but it does not yet support images as images in RSS are... strange.

It would be nice to get at least the first image in a post added to the RSS feed.

**Comment by TkTech** [comment]
Would you object to changing the url to `/@handle.rss`? This seems to be the convention. Mastodon is @handle.rss and @handle.atom, github is @username.atom, etc etc

**Comment by andrewgodwin** [comment]
I'm trying to keep all dynamic URLs ending in trailing slashes as is the Django convention - I think it would be weird to have `/@handle/` and `/@handle.rss`. There's an RSS discovery tag in the page, so any RSS reader should just take the main identity page as input anyway rather than needing users to discover the URL.
