### ISSUE TITLE
Rate limit on posting

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#112]
Each identity should have a (server configurable) rate limit on how often users can post a message. We should probably default it to something like once every 5 seconds.

**Comment by manfre** [comment]
There should probably be a separate rate limit for replying to posts (all or on a per reply_to basis).

**Comment by TkTech** [comment]
There should probably just be a rate limiting decorator on all controllers, even if the default limit is high (for guests) and generous (for signed in users). It can always be tweaked.
