### ISSUE TITLE
Multi-level threading is clunky

### ISSUE THREAD

**Issue by manfre** [jointakahe/takahe#120]
Example of highly nested discussion that requires many clicks to read through: https://ehakat.manfre.net/@andrew@aeracode.org/posts/56/

UX Issues:
* No UI indicating if any of the displayed posts have further children
* Lose nesting history as walk down the discussion tree. To backtrack, must click up through grandparents.

We likely need htmx polling to indicate that there are new replies at the current level and that children have replies. If we don't store the entire discussion tree, we'll need at least the root `Post.id` to make the polling lookups more efficient.

**Comment by andrewgodwin** [comment]
Relaying some discussion from Discord: I don't think we need a full infinitely-nested tree, just "original post", "replies", and "replies to replies (or deeper)".

**Comment by whatSocks** [comment]
was going to make a bug about this but threading is pretty confusing.

**Comment by andrewgodwin** [comment]
Yeah, I need to go check that Mastodon are doing it how I think they are, and then just copy that.
