### ISSUE TITLE
Hashtag parsing mangles Mastodon html <a> containing #anchors

### ISSUE THREAD

**Issue by manfre** [jointakahe/takahe#135]
From https://fosstodon.org/@brettcannon/109468407551365371
(\n added for readability)
```
<a href="https://devguide.python.org/versions/#python-release-cycle" ...>
    <span class="invisible">https://</span>
    <span class="ellipsis">devguide.python.org/versions/#</span>
    <span class="invisible">python-release-cycle</span>
</a>
```
Renders on Takahē as:
```
<p><a href="https://devguide.python.org/versions/<a class=" hashtag"="">#python</a>-release-cycle" rel="nofollow"&gt;https://devguide.python.org/versions/<a class="hashtag" href="/tags/python/">#python</a>-release-cycle</p>
```

**Comment by vibragiel** [comment]
I wanted to tackle this as another low hanging fruit, but went down the hashtag rabbit hole and decided to shelve it, at least for now. There's apparently much more to properly detecting hashtag boundaries, supporting unicode, etc.

For the record, this is how Mastodon handles hashtags:

https://github.com/mastodon/mastodon/blob/78a6b871fe3dae308380ea88132ddadc86a1431e/app/models/tag.rb#L29-L34

And apparently this is how Twitter handles them:

https://github.com/twitter/twitter-text/blob/30e2430d90cff3b46393ea54caf511441983c260/rb/lib/twitter-text/regex.rb#L126-L169

**Comment by andrewgodwin** [comment]
Yeah, this definitely needs more work and a solid test suite - we'll have to move away from the Python "word boundary" identifiers for one.

**Comment by andrewgodwin** [comment]
The new HTML parser I wrote seems to not have this issue, since it only looks for hashtags outside of HTML tags.
