### ISSUE TITLE
[VoiceOver] Reading posts on a feed

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#138]
Trying different rotor options, none seem to work well, so doing the finger drag. 

- it's hard to differentiate one post from the other 
- if there's an @<username> in the text of the post then they get read separately making gaps in the playback, this might be happening to all links
- because each post isn't in it's own container it's harder to get to the little thingies on the top right corner
- there's an non-described UI item on the top right, to the left of the timestamp
- if i tap on the timestamp (it says "1d link" next page says "webpage loaded" and i'm not sure where I am even if i use my eyes.

**Comment by andrewgodwin** [comment]
Closing as feeds are now removed.
