### ISSUE TITLE
Possible timeline bug: post images are shown before content warnings are toggled

### ISSUE THREAD

**Issue by aviflax** [jointakahe/takahe#147]
I just published a post with a CW and an image attachment, and I was surprised to see that on my timeline, the image is shown even while the text is still hidden behind the CW, i.e. when I have not yet “toggled” the post open via the CW.

I happened to notice that the post just below mine, from someone I follow, also had image attachments and a CW, and also was displaying the images by default, even though I hadn’t toggled the CW.

Here’s a cropped screenshot:

<img width="748" alt="image" src="https://user-images.githubusercontent.com/141844/206226265-fdbeb1cd-0a65-4f80-a4ee-7e4a02bc8521.png">

This *seems* like a bug to me, or perhaps a design oversight. Either way, I’d be happy to submit a fix, but I thought I’d ask first @andrewgodwin how you feel about this?

**Comment by andrewgodwin** [comment]
Oh whoops, that's totally a bug. We need to move the image inside the CW element!
