### ISSUE TITLE
Simple photo viewer

### ISSUE THREAD

**Issue by shuuji3** [jointakahe/takahe#161]
The current implementation converts images to WebP format. While WebP itself is great, some browsers such as Google Chrome and Safari (but not Firefox) always download it every time clicking the image, instead of opening it in the browser. It's inconvenient when we want to see enlarg images.

To prevent this a bit annoying download behavior, I'd like a simple photo viewer. I'm thinking about something like this: https://pixelfed.social/p/PixFed/89129948895383552. A similar one can be implemented in _hyperscript.

**Comment by andrewgodwin** [comment]
Yes, that was the intention - just a basic popover box with an X will do.

**Comment by TkTech** [comment]
> The current implementation converts images to WebP format. While WebP itself is great, some browsers such as Google Chrome and Safari (but not Firefox) always download it every time clicking the image, instead of opening it in the browser. It's inconvenient when we want to see enlarg images.

This is resolved for NEW uploads on instances using S3, as we now properly set the `Content-Type`  and `Content-Disposition` headers, which were previously defaulting to octet. Local storage and GCS-backed instances are still borked.
