### ISSUE TITLE
`stator_statorerror` table needs cleanup job

### ISSUE THREAD

**Issue by aviflax** [jointakahe/takahe#166]
<details><summary>query I ran</summary

```sql
SELECT
    table_name,
    pg_size_pretty(table_size) AS table_size,
    pg_size_pretty(indexes_size) AS indexes_size,
    pg_size_pretty(total_size) AS total_size
FROM (
    SELECT
        table_name,
        pg_table_size(table_name) AS table_size,
        pg_indexes_size(table_name) AS indexes_size,
        pg_total_relation_size(table_name) AS total_size
    FROM (
        SELECT ('"' || table_schema || '"."' || table_name || '"') AS table_name
        FROM information_schema.tables
    ) AS all_tables
    ORDER BY total_size DESC
) AS pretty_sizes;
```

[source](https://stackoverflow.com/a/2596678/7012)

</details>

```
   1   │                           table_name                          | table_size | indexes_size | total_size 
   2   │ --------------------------------------------------------------+------------+--------------+------------
   3   │  "public"."stator_statorerror"                                | 824 MB     | 33 MB        | 857 MB
   4   │  "public"."users_identity"                                    | 12 MB      | 1816 kB      | 13 MB
   5   │  "public"."activities_post"                                   | 7336 kB    | 3568 kB      | 11 MB
   6   │  "public"."users_inboxmessage"                                | 10 MB      | 384 kB       | 10 MB
   7   │  "public"."activities_post_mentions"                          | 584 kB     | 1016 kB      | 1600 kB
   8   │  "pg_catalog"."pg_proc"                                       | 856 kB     | 336 kB       | 1192 kB
   9   │  "public"."activities_postattachment"                         | 800 kB     | 104 kB       | 904 kB
  10   │  "pg_catalog"."pg_attribute"                                  | 616 kB     | 256 kB       | 872 kB
  11   │  "public"."activities_fanout"                                 | 464 kB     | 312 kB       | 776 kB
```

I’ve been running Takahē on a DB “server” with 1GB of storage, and this table seems to have caused the disk to fill up, locking up the PostgreSQL process.

I’m not much of a DBA and don’t really want to change that… is this a bug? Or perhaps it reveals a missing feature, some kind of occasional cleanup transaction that would delete old records from this table?

(I’m generally running from tip of `main`, although sometimes with a few days lag. I haven’t run migrations in awhile and tbh it’s a little unclear to me how I’m supposed to know when I need to run them…)

**Comment by andrewgodwin** [comment]
Oh yes, we need something to trim this table periodically. You can just delete everything from it for now.

**Comment by kromonos** [comment]
Mine ran up to 3.8 GB after a week 😂

**Comment by pauloxnet** [comment]
> Oh yes, we need something to trim this table periodically. You can just delete everything from it for now.

So something like `TRUNCATE "public"."stator_statorerror";` ?

> TRUNCATE quickly removes all rows from a set of tables. It has the same effect as an unqualified DELETE on each table, but since it does not actually scan the tables it is faster. Furthermore, it reclaims disk space immediately, rather than requiring a subsequent VACUUM operation. This is most useful on large tables.

https://www.postgresql.org/docs/current/sql-truncate.html

**Comment by kromonos** [comment]
I use `TRUNCATE TABLE public.stator_statorerror RESTART IDENTITY RESTRICT;` for this.

**Comment by pauloxnet** [comment]
I can understand you use `RESTART IDENTITY`, but why you use also `RESTRICT` ?

I read that the effect is:

> Refuse to truncate if any of the tables have foreign-key references from tables that are not listed in the command. This is the default.

But in the code I can't see any foreign-key to the `StatorError` model: 
https://github.com/jointakahe/takahe/blob/main/stator/models.py#L212

**Comment by andrewgodwin** [comment]
I just removed the table in favour of the runner logs and/or using something like Sentry; it was mostly for my debugging use during initial development!
