### ISSUE TITLE
Hash-Tags not "converted" on Mastodon

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#169]
Hash-Tags are simple tags and not "converted" to usable tags on Mastodon. Also, the mentioned account `@AmWriting@a.gup.pe` seems not to be linked.

The original post on Takahe:
![firefox_20221215_150221](https://user-images.githubusercontent.com/1553902/207881188-f22c033d-7a9b-44cb-a897-92f997077235.png)

The post seen on Mastodon:
![firefox_20221215_150252](https://user-images.githubusercontent.com/1553902/207881257-0574ac96-e27d-482d-9338-5b01fc67620d.png)

Edit: Seen on c.im as well as on writing.exchange

**Comment by andrewgodwin** [comment]
Fascinating, I thought Mastodon did its own hashtag linkifying. Will have to dig into this and see if there's some JSON we're not sending over.

**Comment by andrewgodwin** [comment]
Update: I added the missing "tag" items for the hashtags, but they are _still_ not linkifying on Mastodon. I don't know what we're doing wrong, as they look the same as the messages we get from Mastodon now.

**Comment by andrewgodwin** [comment]
OK, this is now fixed (we had to link them with the same URI that was in their tag object).

I could not replicate the mention issue - if it still persists after this fix, let me know and we'll open a new issue for that.
