### ISSUE TITLE
Hide posts from blocked domains

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#172]
Currently, it seems working only half. E.g. when someone I follow shares a post from a domain, which is blocked on the Takahe instance I am, I see this post.  
In my eyes, even those posts should be hidden. Like `if $postDomain == in_array($blockedDomains): skip rendering`

**Comment by andrewgodwin** [comment]
Yup! We also need an individual user-blocking system, and the fix for this will probably come with that.
