### ISSUE TITLE
Hashtag bug also appears with the remote usernames

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#178]
Looks like the bug from the hashtags also appears with the remote usernames:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221216_174432.png)

On Takahe everything seems fine:
![](https://mws.bka.li/sharex/2022/12/firefox_20221216_174645.png)

But on Mastodon, the username `@AmWriting@a.gup.pe` is not linked:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221216_174743.png)

Also, it looks like the link in this post is not translated as expected. Maybe because of the `.blog` TLD?

**Comment by kromonos** [comment]
Another interesting fact is, that the first hashtag was used for the link preview:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221216_183938.png)

**Comment by andrewgodwin** [comment]
Thanks - I wonder if this might be a case-sensitivity problem with the username, now you've typed it out. I'll take a look soon!

**Comment by kromonos** [comment]
It looks like, the gup.pe accounts are all lowercase: https://a.gup.pe/u/AmWriting  
I just made myself such a notation habit, so that hashtags are also good to read for e.g. braille devices. Besides, it is a coding habit. 😄

**Comment by andrewgodwin** [comment]
Ah, the problem was that it was a `Group` type actor, not a `Person`. It should now work after today's commits!
