### ISSUE TITLE
Identity fetch to Akomma (fork of Pleroma) fails due to unsigned request

### ISSUE THREAD

**Issue by TkTech** [jointakahe/takahe#183]
Sentry captured this one. Identity fetch of https://tailswish.industries/users/tulpa fails with `('Client error fetching actor: 401', b'Request not signed')`.

```
ValueError: ('Client error fetching actor: 401', b'Request not signed')
  File "asgiref/sync.py", line 472, in thread_handler
    raise exc_info[1]
  File "stator/models.py", line 171, in atransition_attempt
    next_state = await current_state.handler(self)
  File "users/models/identity.py", line 44, in handle_outdated
    if await identity.fetch_actor():
  File "users/models/identity.py", line 454, in fetch_actor
    raise ValueError(
```

**Comment by andrewgodwin** [comment]
Interesting, because we totally _do_ sign those requests. I'll investigate more locally.

**Comment by andrewgodwin** [comment]
Interesting - it does not like us signing with the System Actor, but it's fine if the request is signed by an individual identity. We must be missing something on the system actor.

**Comment by andrewgodwin** [comment]
It was, in the end, a lack of content-type on the system actor JSON endpoint.
