### ISSUE TITLE
Local emojis are not shown on Mastodon

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#185]
It is correctly shown on Takahe:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221217_152246.png)

But Mastodon .... again:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221217_152134.png)

Did I miss something in setting?
![](https://mws.bka.li/sharex/2022/12/Rambox_20221217_152346.png)

**Comment by manfre** [comment]
The AP message generated for emojis was broken for parts of yesterday. I've tested it with the current main and it is working from Takahe -> Fosstodon.

**Comment by kromonos** [comment]
Hmm ... strange. I'm running on the latest `main`, but got this behavior with writing.exchange and c.im 🤔

**Comment by andrewgodwin** [comment]
Do you know what versions of Mastodon those two sites are running? Maybe they're a variant?

**Comment by kromonos** [comment]
Both are running latest 4.0.2

**Comment by andrewgodwin** [comment]
Very odd. They're working on my 4.0.2 installs as well, so the only thing I can think of is that those specific remote emoji are somehow disabled on the Mastodon side?

**Comment by kromonos** [comment]
I've often seen remote emojis, so I don't think, that they're disabled.

**Comment by andrewgodwin** [comment]
Do you have an account I can follow with my Mastodon server, so you can try again and see if I get them?

**Comment by andrewgodwin** [comment]
I've followed @kromonos@tavern.drow.be - try doing it again

**Comment by kromonos** [comment]
Let's see how you see https://tavern.drow.be/@kromonos@tavern.drow.be/posts/206272/

**Comment by andrewgodwin** [comment]
Well I don't know what's doing it: 
![image](https://user-images.githubusercontent.com/36182/208258526-24fd670a-7198-4ce1-aa2b-a2fe514ad8c7.png)

**Comment by andrewgodwin** [comment]
I've added a new "To ap tag:" entry on the emoji admin in the most recent commit - could you get what it says for this emoji?

**Comment by kromonos** [comment]
It says: `{'id': 'https://tavern.drow.be/emoji/103/', 'type': 'toot:Emoji', 'name': 'takahe', 'icon': {'type': 'Image', 'mediaType': 'image/png', 'url': 'https://mws.bka.li:443/takahe/emoji/_default/takahe.png'}}`

**Comment by andrewgodwin** [comment]
There we go - your emoji URL is returning the status `418 I'm A Teapot` rather than the image

**Comment by kromonos** [comment]
Only, because you used the clear `curl` UserAgent. When you set the agent in curl with `-A "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"` it should work as expected.

**Comment by andrewgodwin** [comment]
Mastodon sets its own special user agent - do you see it trying to get your image in the access logs successfully?

**Comment by kromonos** [comment]
Mastodon is definitely able to download files from my Minio service:
![](https://mws.bka.li/sharex/2022/12/kitty-0.76.0.8_20221217_202250.png)

**Comment by andrewgodwin** [comment]
I don't know what to do, then - there must be something Mastodon doesn't like about your minio responses. Everything else is the same as the stuff on my side that works correctly.

For reference, here is a response from my server that works:
```
HTTP/2 200
cache-control: private, max-age=0
content-disposition: inline; filename="takahe.png"
content-type: image/png
cross-origin-opener-policy: same-origin
date: Sat, 17 Dec 2022 19:32:27 GMT
last-modified: Thu, 15 Dec 2022 08:22:10 GMT
referrer-policy: same-origin
server: WSGIServer/0.2 CPython/3.10.6
vary: Cookie, Origin
x-content-type-options: nosniff
x-frame-options: DENY
content-length: 1633
```

and here is one from yours that Mastodon presumably doesn't like:
```
HTTP/2 200
server: nginx
date: Sat, 17 Dec 2022 19:32:53 GMT
content-type: image/png
content-length: 1633
accept-ranges: bytes
content-security-policy: block-all-mixed-content
etag: "9a139b51b9cfde42848dc308988db011"
last-modified: Sat, 17 Dec 2022 14:19:23 GMT
strict-transport-security: max-age=31536000; includeSubDomains
vary: Origin
vary: Accept-Encoding
x-amz-bucket-region: de-west-0
x-amz-object-lock-mode: COMPLIANCE
x-amz-object-lock-retain-until-date: 2023-06-15T14:19:23.302Z
x-amz-request-id: 1731AB90622816DC
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
x-amz-expiration: expiry-date="Fri, 16 Jun 2023 00:00:00 GMT", rule-id="ce59bldo7pr840vsthhg"
x-amz-version-id: 98f8fdc8-80fb-4786-ae20-28012064dd41
expires: Thu, 31 Dec 2037 23:55:55 GMT
cache-control: max-age=315360000
access-control-allow-origin: *
x-cache: MISS
```

**Comment by kromonos** [comment]
Strange. I have absolutely no hit in my logs, that Mastodon even tries to download the emoji 🤔

**Comment by kromonos** [comment]
OK, next interesting thing:  
![](https://mws.bka.li/sharex/2022/12/Rambox_20221218_012027.png)

**Comment by andrewgodwin** [comment]
Now that's very curious. Is it correct on the non-boost, or missing on both?

**Comment by kromonos** [comment]
Also on non boost, when I open the post on Mastodon:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221218_012259.png)

**Comment by andrewgodwin** [comment]
Aha! A new emoji also doesn't work from my server, the good one must have been cached. Let me try to fix this.

**Comment by andrewgodwin** [comment]
OK, this should be fixed by b6a8737

**Comment by kromonos** [comment]
Can confirm, that it's fixed:  
![](https://mws.bka.li/sharex/2022/12/Rambox_20221218_015432.png)

Now they're fetched, as expected:  
![](https://mws.bka.li/sharex/2022/12/kitty-0.76.0.8_20221218_015547.png)

**Comment by andrewgodwin** [comment]
Lovely, thanks for bearing with me through this!
