### ISSUE TITLE
API paths for mobile apps

### ISSUE THREAD

**Issue by willfurnell** [jointakahe/takahe#199]
A few iOS apps (Mastodon, tooot, Metatext) all seem to need the following API paths:

 - - [18/Dec/2022:21:57:22 +0000] "GET /api/v1/timelines/public?local=true HTTP/2.0" 404 1787 "-" "Metatext/2 CFNetwork/1399 Darwin/22.1.0" "-"
 - - [18/Dec/2022:21:57:22 +0000] "GET /api/v1/instance HTTP/2.0" 404 1756 "-" "Metatext/2 CFNetwork/1399 Darwin/22.1.0" "-"
 - - [18/Dec/2022:21:57:22 +0000] "POST /api/v1/apps HTTP/2.0" 404 1756 "-" "Metatext/2 CFNetwork/1399 Darwin/22.1.0" "-"

Without them they are non-functional

**Comment by manfre** [comment]
`/api/v1/instance` is a Mastodon deprecated ([api docs](https://docs.joinmastodon.org/methods/instance/#v1))

**Comment by andrewgodwin** [comment]
We also already have all three of those API endpoints - @willfurnell what version of Takahē was this on?

**Comment by whatSocks** [comment]
I experienced these issues on Takahē 0.6.0-dev on metatext

**Comment by willfurnell** [comment]
@andrewgodwin This was 0.5.0 (git checkout v0.5.0) using the latest docker image

**Comment by willfurnell** [comment]
I can't see that those views are defined:
```


Using the URLconf defined in takahe.urls, Django tried these URL patterns, in this order:

    manifest.json
    notifications/ [name='notifications']
    local/ [name='local']
    federated/ [name='federated']
    search/ [name='search']
    tags/<hashtag>/ [name='tag']
    explore/ [name='explore']
    explore/tags/ [name='explore-tag']
    follows/ [name='follows']
    settings/ [name='settings']
    settings/security/ [name='settings_security']
    settings/profile/ [name='settings_profile']
    settings/interface/ [name='settings_interface']
    admin/ [name='admin']
    admin/basic/ [name='admin_basic']
    admin/domains/ [name='admin_domains']
    admin/domains/create/ [name='admin_domains_create']
    admin/domains/<domain>/
    admin/domains/<domain>/delete/
    admin/federation/ [name='admin_federation']
    admin/federation/<domain>/ [name='admin_federation_edit']
    admin/users/ [name='admin_users']
    admin/identities/ [name='admin_identities']
    admin/invites/ [name='admin_invites']
    admin/hashtags/ [name='admin_hashtags']
    admin/hashtags/create/ [name='admin_hashtags_create']
    admin/hashtags/<hashtag>/
    admin/hashtags/<hashtag>/delete/
    @<handle>/
    @<handle>/inbox/
    @<handle>/action/
    @<handle>/rss/
    compose/ [name='compose']
    compose/image_upload/ [name='compose_image_upload']
    @<handle>/posts/<int:post_id>/
    @<handle>/posts/<int:post_id>/like/
    @<handle>/posts/<int:post_id>/unlike/
    @<handle>/posts/<int:post_id>/boost/
    @<handle>/posts/<int:post_id>/unboost/
    @<handle>/posts/<int:post_id>/delete/
    @<handle>/posts/<int:post_id>/edit/
    auth/login/ [name='login']
    auth/logout/ [name='logout']
    auth/signup/ [name='signup']
    auth/reset/ [name='trigger_reset']
    auth/reset/<token>/ [name='password_reset']
    @<handle>/activate/
    identity/select/
    identity/create/
    .well-known/webfinger
    .well-known/host-meta
    .well-known/nodeinfo
    nodeinfo/2.0/
    actor/
    .stator/
    djadmin/
    ^media/(?P<path>.*)$

The current path, api/v1/apps, didn’t match any of these.
```

**Comment by andrewgodwin** [comment]
@willfurnell The API is not in 0.5, only in `main` right now! I'm going to close this as invalid as it is there, just not in your version yet :)

@whatSocks That sounds more like a server error than a missing URL issue - if you could open a separate issue with what you see, one of us can get around to running the client against a test server and seeing what breaks.

**Comment by willfurnell** [comment]
I can confirm that building a new docker image from `main` I can now use the API - thanks!
