### ISSUE TITLE
Wrong link for incoming hashtags

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#200]
Incoming hashtags lead to the instance from where they're coming, instead to the local one, even, when they locally already exist:  
![](https://mws.bka.li/sharex/2022/12/hash-tags.png)

**Comment by manfre** [comment]
This is likely due to Hashtags not being included or parsed correctly with the message.

**Comment by TkTech** [comment]
It's being parsed correctly, but the domain used when writing the link is always hardcoded to the post author's domain https://github.com/TkTech/takahe/blob/5ba9ed6428841e9bcf8002a18844813ef797e5a1/activities/models/post.py#L366-L366
