### ISSUE TITLE
[feature?] authentication w/ audon

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#201]
Might be a smell for another issue - but I'm trying to authenticate with the audon app https://audon.space/login

* go here https://audon.space/login
* successfully go to the "authorize" page, enter credentials and tap allow
* see `message | "auth_code_required"` 

<img width="856" alt="Screen Shot 2022-12-18 at 8 50 45 PM" src="https://user-images.githubusercontent.com/2731744/208332616-5a50dad4-170d-4670-9e85-5b0b7d2ad993.png">

**Comment by andrewgodwin** [comment]
Hm, we had to hand-roll our own oauth implementation due to the special way Mastodon does it, so it's quite possible I missed something. I shall investigate soon!

**Comment by andrewgodwin** [comment]
Fixed in 5ab5684

**Comment by whatSocks** [comment]
it works - not getting my avatar in audon but i can make a room.
