### ISSUE TITLE
hyperlinks in posts not coming in

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#203]
Seeing this post boosted into the timeline, it's missing hyperlinks

https://mitra.social/objects/01851b44-3234-f0dd-2c17-aab1b29659f1 

this is what it looks like on takahe:

<img width="620" alt="Screen Shot 2022-12-18 at 9 10 07 PM" src="https://user-images.githubusercontent.com/2731744/208334302-e491f1f4-e415-4d42-9d60-b73621cac6cf.png">

This is what it looks like on mastodon

<img width="319" alt="Screen Shot 2022-12-18 at 9 09 16 PM" src="https://user-images.githubusercontent.com/2731744/208334197-3fc93fca-723e-44c0-919c-db6156158637.png">

**Comment by manfre** [comment]
Mitra is a different ActivityPub server and likely has dialect incompatibles with us right now.

**Comment by TkTech** [comment]
This is fixed in #207, as well as fixing searching posts and users by URL for Mitra.

**Comment by TkTech** [comment]
@andrewgodwin this one should be re-opened

**Comment by andrewgodwin** [comment]
Got it. I just refactored all the HTML handling code into a single place, so at least when we retry this it'll be easier to work on.

**Comment by andrewgodwin** [comment]
@TkTech I redid this to use a custom bleach linkify - I can't make it break now with my tests, but your attempts would be welcome.
