### ISSUE TITLE
[feature] emojo endpoint `/api/v1/custom_emojis` 

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#204]
I wanted to see what emojos were supported on takahe instance, so I went to https://emojos.in but was unable to use the tool, 

`takahe.social's custom emoji API (/api/v1/custom_emojis) returned 400 Bad Request. That's all we know. :(`

https://emojos.in/hachyderm.io?show_all=true

<img width="801" alt="Screen Shot 2022-12-18 at 9 14 33 PM" src="https://user-images.githubusercontent.com/2731744/208334711-f26811d8-5a88-4a86-a3a2-d248d2c2fcc8.png">

**Comment by andrewgodwin** [comment]
The Emoji API was requiring login. This is now fixed!
