### ISSUE TITLE
Images are stored although they already exist.

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#210]
Images are stored although they already exist. This might be a problem for S3 users, who have to pay for every MB transferred.

![](https://mws.bka.li/sharex/2022/12/kitty-0.76.0.8_20221219_141000.png)  
![](https://mws.bka.li/sharex/2022/12/kitty-0.76.0.8_20221219_141227.png)

**Comment by TkTech** [comment]
Just checking the existence of a file costs money with S3. The real solution to this is to hash the file while it's downloading and store the hash on the Identity. My quick fix is just to stop infinite disk growth.

**Comment by andrewgodwin** [comment]
Yeah, this is why I didn't want to store avatar images in the first place and just leave them up to something like Varnish, which does all this for you. I might still change my mind if we can't get a reasonable solution in place.

**Comment by andrewgodwin** [comment]
OK, I have removed avatar storage once again and replaced it with nginx read-through caching where nginx does the proxying for us. I'm going to stick with this for now.
