### ISSUE TITLE
docker-compose.yml sends users to a web page that doesn't exist

### ISSUE THREAD

**Issue by magnus919** [jointakahe/takahe#212]
```
# DO NOT USE THIS IN PRODUCTION - it is for development only due to insecure
# settings and the use of "runserver" versus "gunicorn".
# See https://takahe-server.readthedocs.io/en/latest/installation.html for more
```

This link is a 404.

**Comment by magnus919** [comment]
ok now that I play with it more, I see there's a lot more going on with the `docker-compose.yml`. I'll go play with it in my corner and see if I can work up something 1. that works and 2. might be a little more elegant. Assuming both aspirational goals are met I'll offer it up for PR consideration.

**Comment by andrewgodwin** [comment]
Sure - always happy to have some improvement in there. I don't use compose locally, so I can't maintain it very well.
