### ISSUE TITLE
API show code on OAuth 

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#216]
Apps like Walebird need to verify the login manually via code. To manage this, they send the parameter `response_type` with value `code`:  
`https://babay.icu/oauth/authorize?redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&response_type=code&client_id=asaasasasasa&scope=read%20write%20follow`  

However, the code is not displayed, but can be fetched directly from the database.

**Comment by andrewgodwin** [comment]
Yup, the magic URN for "display the code". We really should add this.

**Comment by whatSocks** [comment]
perhaps similar issue here in this comments section - https://grahammacphee.com/writing/mastodon-blog-comments
