### ISSUE TITLE
docker compose setup should include collectstatic

### ISSUE THREAD

**Issue by JoeGermuska** [jointakahe/takahe#218]
Newb to this project, and fairly green about docker, tbh.

I was trying to work through getting things running locally using `docker compose up` and it seems to me that a line like

`    command: ["/takahe/manage.py", "collectstatic", "--noinput"]`

ought to be added to the [setup service](https://github.com/jointakahe/takahe/blob/main/docker/docker-compose.yml#L56-L58)

**Comment by andrewgodwin** [comment]
Ah yes, the docker image includes it but that won't help if the code is mounted. I'll have to see if someone can help with this soon (I don't use compose personally so it's hard to debug things with it)

**Comment by TkTech** [comment]
The docker-compose in the repository is meant for development and debugging. The debug flag is enabled by default so `collectstatic` is not required. If you're finding you have to manually run collectstatic even when in debug, _that's_ a bug.

**Comment by TkTech** [comment]
Looks like this was partially broken by including nginx in the container, as it was overriding the static path even in debug. Fixed in #230 .
