### ISSUE TITLE
CPU time spent on timeline pages is very high

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#221]
It seems to get worse as the server scales, too, for an unknown reason. Cause is as yet unknown, but it climbs to over 20 seconds when a server has over 10,000 identities and 28,000 posts known to it.

**Comment by andrewgodwin** [comment]
Initial profiling shows that it's happening in the render phase of the view, which is unsurprising given the lazy evaluation.

**Comment by TkTech** [comment]
I think this can be closed with the emoji refactor, timelines are zippy zippy

**Comment by andrewgodwin** [comment]
Yeah they really are way better now, I've noticed that!
