### ISSUE TITLE
Database errors running "python3 manage.py runstator"

### ISSUE THREAD

**Issue by evilko221** [jointakahe/takahe#229]
I'm trying to setup a test installation of Takahe on my local machine.
When I run `docker run --env-file takahe.env --net=host jointakahe/takahe python3 manage.py runstator` I get the following error.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: relation "core_config" does not exist
LINE 1: ... "core_config"."json", "core_config"."image" FROM "core_conf...
                                                             ^
```

takahe.env:
```
TAKAHE_DATABASE_SERVER=postgres://takahe@127.0.0.1:5432/takahe
TAKAHE_MEDIA_BACKEND=local://local
TAKAHE_MAIN_DOMAIN=127.0.0.1
TAKAHE_EMAIL_SERVER=console://console
TAKAHE_EMAIL_FROM=<secret email>
TAKAHE_AUTO_ADMIN_EMAIL=<secret email>
TAKAHE_USE_PROXY_HEADERS=false
TAKAHE_ERROR_EMAILS='["<secret email>"]'
TAKAHE_SECRET_KEY=<secret>
```

I already have an empty user and database for Takahe on my machine.

**Comment by gwagstaff** [comment]
The error "psycopg2.errors.UndefinedTable: relation "core_config" does not exist" indicates your database migrations have not yet been applied. 

We recommend running the docker compose setup, which runs the migration automatically. However if you just need to setup the db the below command will run that command: 
docker run --env-file takahe.env --net=host jointakahe/takahe python3 manage.py migrate

**Comment by andrewgodwin** [comment]
Yes, this means you've not run the migrations - you can read more about that here: https://docs.jointakahe.org/en/latest/installation/#database
