### ISSUE TITLE
[Suggestion] Tunable pauses in stator

### ISSUE THREAD

**Issue by rcarmo** [jointakahe/takahe#232]
I've been experimenting with this on a CPU-constrained system ([notes](https://taoofmac.com/space/blog/2022/12/21/0900)) and wanted to figure out why the stator was consuming a constant 10% of the allocated resources, so I did a little investigation and realized that, for this hardware, the `await.sleep()` calls were a little aggressive (`0.01` in particular).

I think this may be extensible to higher-load environments when the stator has to yield to other things as well, and would certainly be applicable to small single-core VPSes.

I patched mine to have slightly higher pauses, and the CPU load went down... to 3%. 

So it might be a good idea to make these pauses tunable (I see three in `runner.py`, might be as simple as defining a `TAKAHE_TICK_INTERVAL` and setting those to be multipliers, but I haven't yet investigated the effect of tweaking each independently).

**Comment by rcarmo** [comment]
Here's a little sample of the overall CPU load as I tweaked the pauses (large peak is a git resync):

![image](https://user-images.githubusercontent.com/392683/209161340-2660ad29-c3dd-4d05-88c6-023cd8d3e829.png)

**Comment by andrewgodwin** [comment]
Oh, fascinating. We can probably make it longer by default, as well.

What did you change them to? The 0.01 call is only for the test harness mode, which presumably wouldn't affect this. I imagine the main loop's 0.5s one had the main effect?

**Comment by rcarmo** [comment]
It’s really late here, so here’s a quick grep:```bash% grep -n 'await asyncio.sleep(' runner.py77:                    await asyncio.sleep(1.5)89:            await asyncio.sleep(1.1)176:            await asyncio.sleep(0.51)```I tried to pick them so they wouldn’t align with each other or with second boundaries (google for the cicada effect).The performance impact of these will be heavily dependent on the hardware config. I’ll fiddle a bit more with this, took a wide detour from doing CPU testing to trying to set up `nginx` caching on my uWSGI install to remove some noise from the logs… Once that’s done I’ll put up more notes, I suspect.On 22 Dec 2022, at 21:07, Andrew Godwin ***@***.***> wrote:﻿
Oh, fascinating. We can probably make it longer by default, as well.
What did you change them to? The 0.01 call is only for the test harness mode, which presumably wouldn't affect this. I imagine the main loop's 0.5s one had the main effect?

**Comment by rcarmo** [comment]
It’s really late here, so here’s a quick grep:

```bash
% grep -n 'await asyncio.sleep(' runner.py
77:                    await asyncio.sleep(1.5)
89:            await asyncio.sleep(1.1)
176:            await asyncio.sleep(0.51)
```

I tried to pick them so they wouldn’t align with each other or with second boundaries (google for the cicada effect).

The performance impact of these will be heavily dependent on the hardware config. 

I’ll fiddle a bit more with this, took a wide detour from doing CPU testing to trying to set up `nginx` caching on my uWSGI install to remove some noise from the logs… Once that’s done I’ll put up more notes, I suspect.

**Comment by andrewgodwin** [comment]
Only the first sleep is used in the main loop - the second one is for shutdown and the third for testing. I think what I'll do here is add a sort of exponential backoff, where the sleep drops down towards 5 seconds if there's no tasks to be pulled.

**Comment by rcarmo** [comment]
OK, I'll give it a whirl in the next few days and report back.

**Comment by rcarmo** [comment]
Quick test seems to work fine: (peak is again git, and restarting things):

<img width="708" alt="Screenshot 2022-12-23 at 19 49 04" src="https://user-images.githubusercontent.com/392683/209400038-906020ee-96b3-4363-a855-d9e52658d140.png">
