### ISSUE TITLE
UX - view my own profile, share my own username

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#236]
I'm to send my username or profile to someone else (like when making a bug report) and it's not obvious how to do that. 
Tapping on my avatar takes me to the identity select page, and tapping on one of my identities takes me to https://takahe.social/ 

How about, adding to the list:
- adding "view public profile" - user can view their profile and copy a link to it from the URL
- add a "copy username" icon - user can copy their username for easy pasting to someone else

**Comment by andrewgodwin** [comment]
There is a "view profile" link at the bottom of the identity select screen, but yes, it is kind of hidden!

(and on that profile screen you can copy your username with the icon to the right of it)

**Comment by whatSocks** [comment]
oh right it's that giant button. I think my mind edited it out since I assumed if I have multiple identities I wouldn't have to switch identities to see them. My experience comes from user management - usually if i want to check on a list of users I don't have to become the user to check on their profile

**Comment by andrewgodwin** [comment]
Yeah, my idea was to add a "view profile" button on the right end of those rows.
