### ISSUE TITLE
[Feature Wish] Hide Like/Repost counter

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#239]
Maybe identity-based hiding of like and repost counter, because I think, counts are not really healthy.

**Comment by andrewgodwin** [comment]
Yes, I agree - we can add it to the Identity Config system.

**Comment by manfre** [comment]
Added the option to Identity config. Would we want this to be set on a per User basis, instead? Not sure it's worth doing the extra DB hit for this one value.

**Comment by andrewgodwin** [comment]
Nah, User is purely for authentication, I generally want display preferences to be in Identity for now.
