### ISSUE TITLE
Custom CSS

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#240]
Maybe with a database field in basic instance settings. So, that it's not always needed to touch the files on the hard disc. This would also make it possible to continue to follow the base source code via GIT or via the Docker images without always having to apply own customizations when updates are made.

**Comment by andrewgodwin** [comment]
Yes, the plan is to have a per-server and a per-identity override available for this!

**Comment by kromonos** [comment]
Hmm ... Just had an idea ... What if, it's just a "Custom header" field. That would make it possible, to inject also JavaScript, like Matomo or Plausible code.  
I know, many people don't like "tracking", but Matomo and Plausible don't have any privacy issues, since they are self-hosted.  
The only thing, that one would need in the field is to remember to add `<script></script>` and `<style></style>`.  
🤔

**Comment by andrewgodwin** [comment]
Maybe - full header injection is both more dangerous and more fragile though, as it's easy to potentially undo something Takahē needs to work.

**Comment by andrewgodwin** [comment]
This was implemented in https://github.com/jointakahe/takahe/pull/258

**Comment by andrewgodwin** [comment]
Yeah, the custom head is what I meant to refer to - that will allow custom CSS and more.
