### ISSUE TITLE
tooting from toot! - can't make toots

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#248]
see error 

![IMG_0ED623DC5C89-1](https://user-images.githubusercontent.com/2731744/209419309-75504361-887b-4c5b-9024-5790c02ec64a.jpeg)

**Comment by andrewgodwin** [comment]
Fascinating. We'll have to debug this with it connected against a live test server, unfortunately, which means I need to go dig out an ipad at some point.

**Comment by whatSocks** [comment]
this is fixed
