### ISSUE TITLE
Set default visibility for replies

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#256]
The current settings of `unlisted` are really helpful. Sometimes. But I had some discussions with others, who think, that it wouldn't be possible for others to join a longer discussion, when they don't see the answers, because the original post will never be bumped up in a timeline.
I saw on the Fedilab client, that they have a special setting for this:
![](https://mws.bka.li/sharex/2022/12/a0cb6ee0-2f52-4a8d-ad63-a7d02e1df6ee.png)

So I thought, we could get such a setting too? It could be identity based, like the default visibility.

**Comment by andrewgodwin** [comment]
Yes, we can! Won't be too hard to add. I did get complained at for replies being public at first, though, so we'll still default it to unlisted I think.

**Comment by kromonos** [comment]
> I did get complained at for replies being public at first, though, so we'll still default it to unlisted I think.

That's fine for me. FediLab is doing the same, and you have to switch manually to public answers.
