### ISSUE TITLE
Admin notes for domains (e.g. why it's blocked)

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#259]
I would love to get a small text field, I think varchar(254) should be enough, to enter a small reason, when one blocks an instance or a user from the instance.

**Comment by andrewgodwin** [comment]
Is the existing "admin notes" feature on the identity admin page not suitable for this?

**Comment by kromonos** [comment]
Oh, for single identities it is. Sorry, I was not exact enough. My main intention was for blocked domains.

**Comment by andrewgodwin** [comment]
Aha, yes, that we can put on the feature roadmap.
