### ISSUE TITLE
Animated PNG emojis are not translated correctly on Mastodon

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#262]
Example post: https://tavern.drow.be/@kromonos@tavern.drow.be/posts/233450/
![](https://mws.bka.li/sharex/2022/12/Rambox_20221224_201655.png)

On Mastodon:
![](https://mws.bka.li/sharex/2022/12/Rambox_20221224_201716.png)

I've added them as usual via the admin interface:
![](https://mws.bka.li/sharex/2022/12/firefox_20221224_201829.png)

To ap tag:
```
{'id': 'https://tavern.drow.be/emoji/304/', 'type': 'Emoji', 'name': ':dancing_monkey:', 'icon': {'type': 'Image', 'mediaType': 'image/png', 'url': 'https://mws.bka.li:443/takahe-sns/emoji/_default/dancing_monkey.png'}, 'updated': '2022-12-20T21:46:47Z'}
```

The funny thing is, that I got the dancing monkey from a Mastodon server, so I'm sure, they support them.
Example Mastodon post with an animated emoji: https://mas.to/@nkrivera/109564536770076952

**Comment by andrewgodwin** [comment]
This works for me, having just tested it, so I'm not sure what's going wrong here on your end - the fact the emoji isn't appearing at all is odd.

**Comment by andrewgodwin** [comment]
@kromonos Is this still failing for you?

**Comment by andrewgodwin** [comment]
Alright!
