### ISSUE TITLE
Autofill CW when replying to a CWed post

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#268]
Currently, the message would send to the open world. Wouldn't it be better, if the reply would be set into CW too, with the same CW name?

**Comment by manfre** [comment]
Even though I find it annoying that a CW post thread requires so much clicking to expand, I agree we should probably default to chaining it along. It's possible for some one to direct link to the non-CW reply, which bypasses the explicit opt-in readers choose when starting from a feed.

We need a "expand all" button.

**Comment by andrewgodwin** [comment]
Oh yes, this totally needs implementing in the reply compose.

I also had the thought that maybe we could expand all CWs named the same thing at once? That doesn't seem too hard to do with hyperscript.
