### ISSUE TITLE
Local-Only Post Visibility

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#27]
<img width="616" alt="Screen Shot 2022-11-20 at 5 21 23 PM" src="https://user-images.githubusercontent.com/2731744/202929432-e128c467-5311-47d1-9dc3-8118da7c66ab.png">

Learning from hometown the fork of Mastodon, local-only (ie: non-federated) posting can be a blessing. It can also be nice for testing little things (like boosts not ... boosting) in a production environment without broadcasting them to the entire fediverse. 

Check out the Hometown motivation here:

https://github.com/hometown-fork/hometown/wiki/Local-only-posting

The glitch-soc documentation here:

https://glitch-soc.github.io/docs/features/local-only-toots/

**Comment by andrewgodwin** [comment]
Now this is a lovely idea I had not seen. Agreed!
