### ISSUE TITLE
Post canonicalization bug

### ISSUE THREAD

**Issue by tabletcorry** [jointakahe/takahe#282]
Hmm, interesting bug. If I post to Mastodon and Takahē with something like the following:
```
first line

Second line
third line


fourth line
```

Mastodon will store this as:
```
<p>Testing something, will delete this</p><p>Second line<br />Third line</p><p>Fourth line</p>
```

And Takahē will store it as
```
<p>Testing with multiple lines</p>

<p>One blank since the last line<br>No blanks since the last line</p>

<p>Two blanks since the last</p>
```

(sorry. the message content doesn't match because I was copying from several instances, but the raw data is copied from djadmin)

Web clients render the two results roughly the same, but mobile clients render the Takahē result dramatically differently, as seen in the screenshot (confirmed on Ivory and official Mastodon client).

Example post: https://takahe.tabletcorry.com/@corry@takahe.tabletcorry.com/posts/64/

Example rendering in mobile client:
![Screenshot_2022-12-26_at_8 55 46_PM](https://user-images.githubusercontent.com/456754/209613779-d3a1a3fa-9178-4a39-af28-b953bc737e0a.png)

I think the fix is to remove the blank lines from Takahē's post storage? And possibly use a self-closing break tag.

**Comment by andrewgodwin** [comment]
Oh wow, clients are newline sensitive huh? Yes, we can totally remove the extra newlines. I don't think the <br> should matter though.

**Comment by tabletcorry** [comment]
Yeah, it's pretty strange.

Agreed the break tag shouldn't matter, and the only reason to switch would be to more closely align to Mastodon formatting.
