### ISSUE TITLE
When composing a Post with images, it's too easy to skip the "Upload" step

### ISSUE THREAD

**Issue by manfre** [jointakahe/takahe#283]
I keep making Posts with an image selected, but not uploaded. Need some hyperscript to notify when there is an un-uploaded attachment.

**Comment by andrewgodwin** [comment]
I wonder if we should just have the browse field and description field there in the first place and just allow a single image upload? The current process is kind of janky all around.

**Comment by TkTech** [comment]
I personally upload multiple images all the time, would really suck to lose it

**Comment by manfre** [comment]
@TkTech I agree that multiple image support is a must have feature.

**Comment by andrewgodwin** [comment]
OK, OK! Let's try to make the code a bit easier to work with, then.

**Comment by whatSocks** [comment]
I know I've thought image not uploaded since I assumed they were already uploaded. 
Another nice-to-have would be a more salient warning when there's no alt text on the image, like this from hometown: 

https://github.com/mastodon/mastodon/pull/22831

**Comment by andrewgodwin** [comment]
This has been solved by me just removing this whole compose image upload thing. You can now upload only 0 or 1 images, since we will push users to an app for most composing.
