### ISSUE TITLE
activities.hashtag running the whole day

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#286]
Currently, I've set up 2 stators only for `activities.hashtag` and still, it seems to run the whole day long. My instance is currently counting 8964 hashtags, but I bet, most of them are used one time only and that's it. Do they need to be updated that regular?  
My idea would be, as soon as a hashtag is received with a post, set them to `outdated` and let the stator do his job then. Else, they don't need to get touched, do they?

**Comment by andrewgodwin** [comment]
Yeah, we just need to redo the hashtag system I think.

**Comment by manfre** [comment]
I made this mess, I'll take a stab at fixing it up.

**Comment by andrewgodwin** [comment]
Oh, I was actually quite interested in sitting down and rethinking a bit, but interested to see what you want to do too.

**Comment by andrewgodwin** [comment]
Do we think this is better now?

**Comment by andrewgodwin** [comment]
Lovely, I'll close this then.
