### ISSUE TITLE
[Suggestion] extensions in cacheable media

### ISSUE THREAD

**Issue by rcarmo** [jointakahe/takahe#287]
Hi there, 

I'm trying to tune caching in Takahe, and have noticed that media/proxy URLs don't have a file extension. Since I use Cloudflare, having an extension [would actually simplify edge caching](https://developers.cloudflare.com/cache/about/default-cache-behavior). 

That can be easily verified by running a public URL via https://redbot.org.

For instance, using my test instance (which is behind Cloudflare and I've been tuning `nginx` caching on):

* [This uploaded PNG file is cached by Cloudflare](https://redbot.org/?uri=https://insightful.systems/media/profile_images/2022/12/20/BQvqy_viXWmdB4leJvlHludq5Ns.png)

```
HTTP/1.1 200 OK
Date: Tue, 27 Dec 2022 13:54:13 GMT
Content-Type: image/png
Content-Length: 27432
Connection: keep-alive
Cache-Control: public, max-age=14400
Content-Disposition: inline;
        filename="BQvqy_viXWmdB4leJvlHludq5Ns.png
        4;
Cross-Origin-Opener-Policy: same-origin
Last-Modified: Tue, 20 Dec 2022 23:54:47 GMT
Referrer-Policy: same-origin
Vary: Cookie, Origin
X-Cache: MISS
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
CF-Cache-Status: HIT
Age: 206
Accept-Ranges: bytes
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudfl
        are.com\/report\/v3?s=wkjpQCMvFt3uHOv%2Bvm4UQk25QLyn0uNeOa
        i5i0TymG9b9WgTThlzuEOI6LwARUePPjkuYNp%2B1m%2BvHeJ1XzQDY3hp
        eUCBpltP%2BqvPubX5y5a3dYqISQjpl0xY4DXdz%2B6Sd85siVsfiL54LT
        OuFr7cgAI%3D"}],"group":"cf-
        nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-
        nel","max_age":604800}
Server: cloudflare
CF-RAY: 78028c0348e597cf-SJC
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

* [This proxied banner image is not cached by Cloudflare](https://redbot.org/?uri=https://insightful.systems/proxy/identity_image/27/)

```
HTTP/1.1 200 OK
Date: Tue, 27 Dec 2022 13:52:06 GMT
Content-Type: image/jpeg
Content-Length: 173674
Connection: keep-alive
Cache-Control: public, max-age=3600
Cross-Origin-Opener-Policy: same-origin
Referrer-Policy: same-origin
Vary: Cookie, Origin
X-Cache: HIT
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
CF-Cache-Status: DYNAMIC
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudfl
        are.com\/report\/v3?s=6bwnBNZIcLQYXjvkU6JuuskWYKpOi5qo1aMe
        JnP2CdMeTLtTfmeUzBo3Isbc06idpo0IZ48%2FFtO4E3%2BYlgi9URPQTW
        jAvbHxL3AvcPzQBEn34xM0IkU0u%2BzYsc%2F8EeMOlRnDALqLtke2dHV7
        hcV5dWQ%3D"}],"group":"cf-
        nel","max_age":604800}
NEL: {"success_fraction":0,"report_to":"cf-
        nel","max_age":604800}
Server: cloudflare
CF-RAY: 780288e4adc8d009-SJC
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
```

**Comment by andrewgodwin** [comment]
Yeah, we can't reliably give the extensions unfortunately - with Cloudflare, I suggest just telling it to respect the cache-control headers we send out for the proxy URLs, as those will be more correct.

**Comment by rcarmo** [comment]
That works, but you end up sacrificing a page rule - which on free tiers may not be available anymore once you enforce HTTPs and other basic amenities. The extensions could be autogenerated from the reported remote media type for proxied content...

**Comment by andrewgodwin** [comment]
If we land https://github.com/jointakahe/takahe/pull/294 we can probably move it in there too, but we're figuring that out still.

**Comment by andrewgodwin** [comment]
OK, reopening this so we can actually fix it.

**Comment by rcarmo** [comment]
Thanks, I'll pull to my test instance and do some testing!

**Comment by rcarmo** [comment]
Yep, I'm now getting `cf-cache-status: HIT" on proxied images, which should limit load a _lot_.
