### ISSUE TITLE
Oauth login/authorization for Mammoth (iOS) not working

### ISSUE THREAD

**Issue by colin** [jointakahe/takahe#290]
I've been trying [Mammoth](https://getmammoth.app/) as an iOS client app for the Mastodon API of my Takahe instance and it seems stuck in the initial oauth flow.

From what I could piece together so far (traceback below), it seems to send the necessary data as URL params in a POST request with `CONTENT_TYPE = 'application/json'` and Takahe is theoretically supporting both POST params as well as JSON data
https://github.com/jointakahe/takahe/blob/218aabc5979cc2f30168ec3d82e1aa7c19795606/api/views/oauth.py#L81
but the content type is triggering JSON decoding which then fails on an empty request body
https://github.com/jointakahe/takahe/blob/218aabc5979cc2f30168ec3d82e1aa7c19795606/api/parser.py#L14-L19

I don't think I speak enough Django/Python to suggest a good solution, but maybe checking for both `request.content_type == "application/json"`as well as the (non-empty) existence of a `request.body` in L14 before trying the JSON decoding would already fall back to the alternative POST data solution that might make this request from the client app work?

<details>
<summary>
Full error for reference:
</summary>

> Internal Server Error: /oauth/token
> 
> JSONDecodeError at /oauth/token
> Expecting value: line 1 column 1 (char 0)
> 
> Request Method: POST
> Request URL: https://social.colinschlueter.com/oauth/token?grant_type=authorization_code&code=XXX&redirect_uri=mammoth%3A%2F%2FaddNewInstance&client_id=tk-XXX&client_secret=XXX&scope=read%20write%20follow%20push
> Django Version: 4.1.4
> Python Executable: /usr/local/bin/python3
> Python Version: 3.11.1
> Python Path: ['/takahe', '/usr/local/bin', '/usr/local/lib/python311.zip', '/usr/local/lib/python3.11', '/usr/local/lib/python3.11/lib-dynload', '/usr/local/lib/python3.11/site-packages']
> Server time: Tue, 27 Dec 2022 12:09:32 +0000
> Installed Applications:
> ['django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'corsheaders',
>  'django_htmx',
>  'core',
>  'activities',
>  'api',
>  'mediaproxy',
>  'stator',
>  'users']
> Installed Middleware:
> ['core.middleware.SentryTaggingMiddleware',
>  'django.middleware.security.SecurityMiddleware',
>  'corsheaders.middleware.CorsMiddleware',
>  'whitenoise.middleware.WhiteNoiseMiddleware',
>  'django.contrib.sessions.middleware.SessionMiddleware',
>  'django.middleware.common.CommonMiddleware',
>  'django.middleware.csrf.CsrfViewMiddleware',
>  'django.contrib.auth.middleware.AuthenticationMiddleware',
>  'django.contrib.messages.middleware.MessageMiddleware',
>  'django.middleware.clickjacking.XFrameOptionsMiddleware',
>  'django_htmx.middleware.HtmxMiddleware',
>  'core.middleware.HeadersMiddleware',
>  'core.middleware.ConfigLoadingMiddleware',
>  'api.middleware.ApiTokenMiddleware',
>  'users.middleware.IdentityMiddleware']
> 
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
>     response = get_response(request)
>   File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
>     response = wrapped_callback(request, *callback_args, **callback_kwargs)
>   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 103, in view
>     return self.dispatch(request, *args, **kwargs)
>   File "/usr/local/lib/python3.11/site-packages/django/utils/decorators.py", line 46, in _wrapper
>     return bound_method(*args, **kwargs)
>   File "/usr/local/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
>     return view_func(*args, **kwargs)
>   File "/usr/local/lib/python3.11/site-packages/django/views/generic/base.py", line 142, in dispatch
>     return handler(request, *args, **kwargs)
>   File "/takahe/api/views/oauth.py", line 81, in post
>     post_data = FormOrJsonParser().parse_body(request)
>   File "/takahe/api/parser.py", line 15, in parse_body
>     return json.loads(request.body)
>   File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.11/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.11/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> 
> Exception Type: JSONDecodeError at /oauth/token
> Exception Value: Expecting value: line 1 column 1 (char 0)
> Raised during: api.views.oauth.TokenView
> Request information:
> USER: AnonymousUser
> 
> GET:
> grant_type = 'authorization_code'
> code = 'XXX'
> redirect_uri = 'mammoth://addNewInstance'
> client_id = 'tk-XXX'
> client_secret = 'XXX'
> scope = 'read write follow push'
> 
> POST: No POST data
> 
> FILES: No FILES data
> 
> COOKIES: No cookie data
> 
> META:
> CONTENT_LENGTH = '0'
> CONTENT_TYPE = 'application/json'
> HTTP_ACCEPT = 'application/json'
> HTTP_ACCEPT_ENCODING = 'gzip, deflate, br'
> HTTP_ACCEPT_LANGUAGE = 'en-GB,en;q=0.9'
> HTTP_CONNECTION = 'close'
> HTTP_FLY_CLIENT_IP = '2001:9e8:229:6800:a01f:7eab:5a22:1fb8'
> HTTP_FLY_FORWARDED_PORT = '443'
> HTTP_FLY_FORWARDED_PROTO = 'https'
> HTTP_FLY_FORWARDED_SSL = 'on'
> HTTP_FLY_REGION = 'fra'
> HTTP_FLY_REQUEST_ID = '01GN9QSSSFHS4P9ZMVV57R900T-fra'
> HTTP_FLY_TRACEPARENT = '00-ea54a6194480957253d551b01d80b5c3-9940d3ea3bdbeca0-00'
> HTTP_FLY_TRACESTATE = ''
> HTTP_HOST = 'social.colinschlueter.com'
> HTTP_USER_AGENT = 'Mastodon/40 CFNetwork/1402.0.8 Darwin/22.2.0'
> HTTP_VIA = '2 fly.io'
> HTTP_X_FORWARDED_FOR = '2001:9e8:229:6800:a01f:7eab:5a22:1fb8, 2a09:8280:1::3:bcec, 172.16.16.250'
> HTTP_X_FORWARDED_PORT = '443'
> HTTP_X_FORWARDED_PROTO = 'https'
> HTTP_X_FORWARDED_SSL = 'on'
> HTTP_X_REQUEST_START = 't=1672142972719167'
> PATH_INFO = '/oauth/token'
> QUERY_STRING = 'grant_type=authorization_code&code=XXX&redirect_uri=mammoth%3A%2F%2FaddNewInstance&client_id=tk-XXX&client_secret=XXX&scope=read%20write%20follow%20push'
> RAW_URI = '/oauth/token?grant_type=authorization_code&code=XXX&redirect_uri=mammoth%3A%2F%2FaddNewInstance&client_id=tk-XXX&client_secret=XXX&scope=read%20write%20follow%20push'
> REMOTE_ADDR = '127.0.0.1'
> REMOTE_PORT = '58050'
> REQUEST_METHOD = 'POST'
> SCRIPT_NAME = ''
> SERVER_NAME = '0.0.0.0'
> SERVER_PORT = '8001'
> SERVER_PROTOCOL = 'HTTP/1.1'
> SERVER_SOFTWARE = 'gunicorn/20.1.0'
> gunicorn.socket = <socket.socket fd=10, family=2, type=1, proto=0, laddr=('127.0.0.1', 8001), raddr=('127.0.0.1', 58050)>
> wsgi.errors = <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7fef225e63b0>
> wsgi.file_wrapper = <class 'gunicorn.http.wsgi.FileWrapper'>
> wsgi.input = <gunicorn.http.body.Body object at 0x7fef227aebd0>
> wsgi.input_terminated = True
> wsgi.multiprocess = True
> wsgi.multithread = False
> wsgi.run_once = False
> wsgi.url_scheme = 'https'
> wsgi.version = '(1, 0)'

</details>

**Comment by andrewgodwin** [comment]
OK, I've pushed up a change that should do as you suggest - have a go and see if it fixes it?

**Comment by rcarmo** [comment]
I've just tried the latest Mammoth beta with my server (which runs git tip) and it doesn't work for me either, nor does Tooot. 

MetaText and Tusker, however, were able to log in (although I'm not getting updated posts in MetaText for some reason)....

**Comment by TkTech** [comment]
I'm working on oauth issues today.

**Comment by cosmin** [comment]
I don't have access to Mammoth yet but I'm fairly certain this should be fixed by #338 which should have plugged all the known issues in the oauth flow.

**Comment by andrewgodwin** [comment]
@colin Are you able to re-test with all the recent oauth fixes and see if this is fixed?

**Comment by jph7C1** [comment]
I set up a test server on my Mac via the instructions for using Docker and the I put Nginx in front of it as a reverse proxy to satisfy SSL requirements. On the same Mac I attempted to log into the server with three TestFlight clients. Woolly and Mastoot authenticated ok, Mammoth did not. Mammoth kicks you out into Safari to authorize. Of the iOS apps I've used that's unique, the others use a web view within the app.

This is what I pulled from the logs of the Nginx proxy. Mammoth was the only one that seemed to log anything to the docker container. "bad request" I've reformatted to make it readable. The format is a black with the POST request, then the HTTP response for that request. Mammoth is first, then Woolly and Mastoot.

```
POST /oauth/authorize
	response_type = code
	redirect_uri  = mammoth://addNewInstance
	scope         = read write follow push
	client_id     = tk--c0y1WISCpmBoymK3lmfmw

HTTP/1.1 302 0 https://lilith.jph.io/oauth/authorize?response_type=code&redirect_uri=mammoth://addNewInstance&scope=read write follow push&client_id=tk--c0y1WISCpmBoymK3lmfmw

POST /oauth/token
	grant_type    = authorization_code
	code          = 7W26JAkX1E5B9YtGOGBaSz765cuitczvQzo0H6onHD0h9dDED2ForQdVyQ
	redirect_uri  = mammoth://addNewInstance
	client_id     = tk--c0y1WISCpmBoymK3lmfmw
	client_secret = qZdMGIghmKrbW3G2Foc-QlzGiT5b1E_6yvl5MAQfjZ00BGVEJLbSBw
	scope         = read write follow push

HTTP/1.1 400 31 "-" "Mammoth/62 CFNetwork/1402.0.8 Darwin/22.2.0
	
Docker:
	Bad Request: /oauth/token


POST /oauth/authorize
	client_id     = tk-Y61w9L4LKGMy3EzfOKcyiw
	scope         = read+write+follow+push
	redirect_uri  = woolly://auth
	response_type = code

HTTP/1.1 302 0 https://lilith.jph.io/oauth/authorize?client_id=tk-Y61w9L4LKGMy3EzfOKcyiw&scope=read+write+follow+push&redirect_uri=woolly://auth&response_type=code

POST /oauth/token

HTTP/1.1 200 163 "-" "Woolly/28 CFNetwork/1402.0.8 Darwin/22.2.0"


POST /oauth/authorize
	response_type = code
	redirect_uri  = mastoot://oauth
	scope         = read write follow push
	client_id     = tk-dhbqiN5WJ5THptsbieb9EQ

HTTP/1.1 302 0 https://lilith.jph.io/oauth/authorize?response_type=code&redirect_uri=mastoot://oauth&scope=read write follow push&client_id=tk-dhbqiN5WJ5THptsbieb9EQ

POST /oauth/token

HTTP/1.1 200 163 "-" "Mastoot/106 CFNetwork/1402.0.8 Darwin/22.2.0
```

**Comment by cosmin** [comment]
I finally got access to Mammoth, and I just updated my instance to current tip of `main` and can confirm it does not work. I'll do some digging.
