### ISSUE TITLE
No 'See original' with no mastodon instances

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#302]
With Pleroma:  
![](https://mws.bka.li/sharex/2022/12/firefox_20221228_163638.png)

And MissKey:
![](https://mws.bka.li/sharex/2022/12/firefox_20221228_163537.png)

**Comment by andrewgodwin** [comment]
Can we get a URL to that second, broken post?

**Comment by kromonos** [comment]
oh. Sure.

https://tavern.drow.be/@alsternerd@social.alster.space/posts/241051/  -> Sadly, I can't find this on the remote instance
and 
https://tavern.drow.be/@me@cybre.club/posts/240899/ -> https://cybre.club/notes/99b7k2qxh3

**Comment by andrewgodwin** [comment]
OK, I can't pull the posts to verify, but I think that should fix it.
