### ISSUE TITLE
Open post with another identity

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#305]
Sometimes I come across single posts I want to share, but with another identity I have. So I would love to see an easy way, like through extending the post menu, with an “Open with ...” entry, to open the post with another identity.

![](https://mws.bka.li/sharex/2022/12/firefox_20221228_175321.png)

**Comment by andrewgodwin** [comment]
Hmm, this is tricky because identities are session-based, so this would be more "switch the session to another identity and preserve the URL". Will put it down as a feature request.

**Comment by manfre** [comment]
Another option could be to use `?asIdentity=otherme@example.com`. The middleware that pulls identity from the session could do the "is this yours" check and swap it in to `request.identity`. We can selectively chain the `?asIdentity=` to forms and `<a>` where appropriate with a hyperscript `onload` for any classed with `can-chain-identity`.

**Comment by AstraLuma** [comment]
Is this still valid with the new UI?
