### ISSUE TITLE
Boosts appear as normal posts in client API

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#313]
It looks like, there's a flag missing in the API, because I don't see the reshared as reshared in Tusky 20.  
On the WebUI:  
![](https://mws.bka.li/sharex/2022/12/Rambox_20221229_080220.png)

Takahe account in Tusky:  
![](https://mws.bka.li/sharex/2022/12/1d4d9d40-be01-4f2f-9838-06fc0206c455.png)

Mastodon account un Tusky:  
![](https://mws.bka.li/sharex/2022/12/d8d17ca4-3f65-4217-bb16-8ce68f27c385.png)  

I don't follow the account of Pallenberg with absolutely no account.

**Comment by andrewgodwin** [comment]
Yes, this is a known issue with the API where boosts come through as normal posts rather than boosts! We didn't have a github issue for it though, so this can be that.
