### ISSUE TITLE
[help!] [docker] trying to rebuild my image

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#32]
Getting stuck trying to rebuild my image, I have tried many combinations of docker build, each failing in their own different way. Here's one:

➜  takahe git:(main) ✗ docker compose -f docker/docker-compose.yml up --build
[+] Building 0.4s (9/11)
 => [internal] load build definition from Dockerfile                                                                                                                                      0.0s
 => => transferring dockerfile: 592B                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/python:3.11.0-slim-buster                                                                                                              0.3s
 => [internal] load build context                                                                                                                                                         0.0s
 => => transferring context: 630B                                                                                                                                                         0.0s
 => [1/7] FROM docker.io/library/python:3.11.0-slim-buster@sha256:e3168357ada3287cda4c79ecae7f5103cb4d071d9b610a1d9380ea4b7cfc981f                                                        0.0s
 => CACHED [2/7] RUN apt-get update && apt-get -y install libpq-dev python3-dev build-essential                                                                                           0.0s
 => CACHED [3/7] COPY . /takahe                                                                                                                                                           0.0s
 => CACHED [4/7] WORKDIR /takahe                                                                                                                                                          0.0s
 => ERROR [5/7] COPY requirements.txt requirements.txt

**Comment by andrewgodwin** [comment]
To build an image, the best way is `make image` from the root directory - I don't think docker-compose understands how.
