### ISSUE TITLE
Misskey accounts unable to follow

### ISSUE THREAD

**Issue by alcapurrias** [jointakahe/takahe#323]
I have 2 Misskey instances and was able to locate and request to follow both of my accounts, but neither was able to successfully follow back. In Takahē I can see that I am following them and they are following me, but in Misskey it shows that following the Takahē account is still pending - it appears communication isn't getting back to Misskey to tell it that the follow successfully went through.

**Comment by andrewgodwin** [comment]
So, the problem with federation where it fails on the _other_ end is that I don't know what we need to fix about our `Accept.Follow` messages without some insight from someone who can peer into the Misskey database - as far as I know, we try to match Mastodon quite closely, but we have some subtle differences in our context and URLs that might (?) be the issue.

Anyway, all this is to say, this is totally a valid bug, but also one we cannot solve without a Misskey person around.

**Comment by vitalyster** [comment]
@andrewgodwin I'm using my own ActivityPub implementation and requests from Takahe side come with invalid `Accept: [application/json]` header and I respond 400 to it, not sure why some other software accept that header

**Comment by vitalyster** [comment]
Well, I checked the code and see the problem on my side too: you are sending generic `application/xml` and `application/json` Accept headers in host-meta and webfinger requests, while correct content type is `application/xrd+xml` and `application/jrd+json` respectively. But generic content-types should be acceptable too, I added generic types as fallbacks and now federation should work, but I think some other implementations may expect correct types too.

**Comment by andrewgodwin** [comment]
Aha, I didn't spot the extended mimetypes for those endpoints in the webfinger spec! I'll update our end to return them too. Thanks for spotting that!

**Comment by andrewgodwin** [comment]
(I do think it's important to accept them generically, as some people are static-hosting those two endpoints and I doubt their static servers will send the exact right mimetype)

**Comment by andrewgodwin** [comment]
@vitalyster You also said request from us come with `Accept: application/json`, but it should be `Accept: application/ld+json` in all our signed-fetch code - what URL were we trying to hit with the wrong header?

**Comment by vitalyster** [comment]
I think all these generic requests came from host-meta/webfinger requests so now it is fixed.
But this issue should be open because we solve different issue but original Misskey issue still not triaged :)

**Comment by andrewgodwin** [comment]
OK! Let me know how I can help - I appreciate you looking into this.

**Comment by gerwitz** [comment]
I have the same behavior with my Akkoma instances (follows from Akkoma to Takahē succeed but the acceptance is not processed so they are never known to be accepted by Akkoma).

So far, I haven’t found any useful logging about this, but will report here if I find it…

**Comment by shuuji3** [comment]
Hi, I'm exploring interoperability between Misskey and Takahē now and encountered the same issue. This still occurs on Firefish (previously, Calckey) which is a fork of Misskey.

I set up a test Misskey server and tried to follow Takahē account and found the following error on the Misskey's server log:


```log
{"level":30,"time":1691901041198,"pid":167,"hostname":"web-76b84b9549-r6mdl","reqId":"req-145","req":{"method":"POST","url":"/users/9ichcwe2gv/inbox","hostname":"misskey.shuuji3.xyz","remoteAddress":"10.42.0.154","remotePort":36758},"msg":"incoming request"}
{"level":30,"time":1691901041203,"pid":167,"hostname":"web-76b84b9549-r6mdl","reqId":"req-145","res":{"statusCode":202},"responseTime":4.589717864990234,"msg":"request completed"}
VERB 1	[queue inbox]	active id=3 attempts=2/8 age=10ms
VERB 1	[queue inbox]	{
  "id": "https://misskey.shuuji3.xyz/follows/9icii7p8im#accept",
  "type": "Accept",
  "actor": "https://takahe.social/@shuuji3@takahe.social/",
  "object": {
    "id": "https://misskey.shuuji3.xyz/follows/9icii7p8im",
    "type": "Follow",
    "actor": "https://misskey.shuuji3.xyz/users/9ichcwe2gv",
    "object": "https://takahe.social/@shuuji3@takahe.social/"
  }
}
WARN 1	[queue inbox]	failed(UnrecoverableError: skip: signerHost(takahe.social) !== activity.id host(misskey.shuuji3.xyz) id=3 attempts=1/8 age=29ms activity=https://misskey.shuuji3.xyz/follows/9icii7p8im#accept
```

So Misskey is dropping the final `Accept` ActivityPub response to the `Follow` request from the Takahē server.

On the other hand, Mastodon returns this `Accept` object in response to the same follow action:

```log
VERB 1	[queue inbox]	active id=10 attempts=2/8 age=7ms
VERB 1	[queue inbox]	{
  "id": "https://mastodon.social/users/shuuji3#accepts/follows/",
  "type": "Accept",
  "actor": "https://mastodon.social/users/shuuji3",
  "object": {
    "id": "https://misskey.shuuji3.xyz/follows/9id2cc6uj7",
    "type": "Follow",
    "actor": "https://misskey.shuuji3.xyz/users/9ichcwe2gv",
    "object": "https://mastodon.social/users/shuuji3"
  }
}
INFO 1	[remote ap]	Accept: https://mastodon.social/users/shuuji3#accepts/follows/
```

I suspect `id` is not properly composed. I'm still learning ActivityPub spec and am not confident about the signing process etc. but will try solving this issue because it prevents these relatively popular servers from following the Takahē account in the first stage.

**Comment by andrewgodwin** [comment]
Ahh fascinating, misskey is validating that the signing host matches the object ID - which would be true for every other activitypub server except Takahē, since we obvious have the varied hostnames.

I think fixing this would involve making the AP IDs of these objects just match the actor hostname - they are invented at JSON creation time rather than stored in the database, so I don't think that's too difficult?

**Comment by shuuji3** [comment]
Thanks for the hint.:+1: Yes, we need to choose the correct hostname here. I'll look into the places around the inbox and follow models.

**Comment by AstraLuma** [comment]
So this is happening again to me.

Talking on fedi, @aprl@fediverse.gay said:

> okay i can instantly tell you what the issue is! the accept activity needs its own id for the accept activity, coming from the takahe host. you are not allowed to reuse the follow activity you received for that

(Apparently someone else made the same mistake)

Are we allowed to make up a non-existent URL for this, or does it have to actually validate? If we need a real URL for it, does it need to exist in the DB or can we synthesize one based on the Following list and maybe some clever crypto?

**Comment by andrewgodwin** [comment]
You can make up URLs (including by adding fragments to the end of them), but I thought we _did_ do that specifically for this here: https://github.com/jointakahe/takahe/blob/e577d020ee9857eb78fab4664b6abc436172c099/users/models/follow.py#L278

**Comment by AstraLuma** [comment]
Yeah, but for LD signatures, it has to be one of Takahē's URLs, not the remote server's.

In the above data, the Accept activity has the URL of `https://misskey.shuuji3.xyz/follows/9icii7p8im#accept` despite the fact that it originates at `takahe.social`.

**Comment by andrewgodwin** [comment]
Ahhhh, right! We can switch that to `self.uri` then and easily fix this.

(also, another reason to drop LD sigs)
