### ISSUE TITLE
Local follows not showing up as notifications

### ISSUE THREAD

**Issue by colin** [jointakahe/takahe#326]
I'm not sure whether it has to do with my configuration, but it looks like local follow events (account A on a Takahe instance starts following account B on the same instance) are not showing up in the notifications - is that correct/intentional?
If I follow an account on my Takahe instance from both another local account as well as a https://mstdn.social account, only the latter is generating an entry in `activities_timelineevent` and is shown at `/notifications`.

**Comment by andrewgodwin** [comment]
Hah, yes, we had a different path for local follows that wasn't adding the event!
