### ISSUE TITLE
Fix poll date display

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#327]
I was able to boost a poll onto takahe (searching doesn't work) and see that the date is not the correct format 

https://takahe.social/@literally@fedibird.com/posts/11684/ 

takahe:

<img width="630" alt="Screen Shot 2022-12-30 at 3 20 45 PM" src="https://user-images.githubusercontent.com/2731744/210109111-04a964b4-b0c5-43aa-9500-668303c24034.png">

fedibird:

https://fedibird.com/@literally/109604474570736104 (try searching this)

<img width="347" alt="Screen Shot 2022-12-30 at 3 21 15 PM" src="https://user-images.githubusercontent.com/2731744/210109138-476b2510-37d7-407c-84c3-a18bdd72b00c.png">

**Comment by andrewgodwin** [comment]
Yes, polls are just not entirely working yet!

**Comment by manfre** [comment]
https://github.com/jointakahe/takahe/commit/fc8b5be4a0c8f5f5d6dbe36aea4da12eab3dfbbb improved the formatting a little bit, but we should add a `timedeltalong` template tag for the more verbose display.
