### ISSUE TITLE
[metatext] link previews not showing

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#330]
Using metatext, I logged in and checked the same fedibird account with a mastodon account and a takahe account.

Link previews show from mastodon, don't show from takahe

https://takahe.social/@literally@takahe.social/posts/12109/

**Comment by andrewgodwin** [comment]
Link previews are a feature supplied by the server, so this is not supposed to work (and we don't plan on implementing them yet). I'm going to close this as it's not a separate bug!
