### ISSUE TITLE
Icon to mark image as having alt text or not

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#336]
This isn't really a issue on desktop but visiting takahe on mobile and trying to read image alt text results in a lot of clicking of images, which opens the file (and not in a nice image viewer). If there were an icon, it would save some time and confusion. 

Some examples UIs [are discussed here](https://github.com/mastodon/mastodon/pull/22831)  

I like this one since it's unobtrusive

https://github.com/mastodon/mastodon/pull/22831#issuecomment-1367638566

**Comment by shuuji3** [comment]
I’m currently working on #161 and it will have a caption at the bottom of the image.

Also, it would a good idea to add some icon to indicate the existence/non-existence of alt text.

**Comment by andrewgodwin** [comment]
I'd still like an icon for this, but with the new image viewer I think it's a lot less important.
