### ISSUE TITLE
Sometimes when I upload an image, it is turned upside-down

### ISSUE THREAD

**Issue by aviflax** [jointakahe/takahe#341]
I’m not 100% sure but I think this has happened either exclusively, or mostly, when I upload an HEIF image in Mobile Safari via the “Photo Library” picker. I’ll try to start keeping track of when this happens and when it doesn’t.

Here’s a screenshot illustrating this:

![54485BB1-F673-4559-A685-B742AF5D31C0](https://user-images.githubusercontent.com/141844/210177245-b8fd3eec-2a64-4da0-a396-fb46face2034.png)

At the time I was running on da00a67, and using the Dockerfile so I’m pretty sure this isn’t a Python dependency management problem. (Or at least, what I mean is, at least it’s not a case of me installing a different set of deps than the code intends, that kind of thing.)

**Comment by aviflax** [comment]
It’s not just HEIF — I just tried uploading a PNG in the compose screen (the above screenshot, actually, which was a little disorienting) and the same thing happened. So it might still be related somehow to using the “Photo Library” picker, I suppose. I’ll try to test that out as well.

**Comment by andrewgodwin** [comment]
Hmm, fascinating. I wonder if these are being rotated by iOS internally for display based on the EXIF data but actually still have the pixel data upside down?

**Comment by TkTech** [comment]
> Hmm, fascinating. I wonder if these are being rotated by iOS internally for display based on the EXIF data but actually still have the pixel data upside down?

That's exactly what's happening.

**Comment by TkTech** [comment]
https://pillow.readthedocs.io/en/latest/reference/ImageOps.html#PIL.ImageOps.exif_transpose needs to be called just after the image is opened and before resizing.

**Comment by aviflax** [comment]
🎉 thanks so much y’all!
