### ISSUE TITLE
UI: Handle many notifications about boosts

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#35]
<img width="680" alt="Screen Shot 2022-11-22 at 6 45 44 PM" src="https://user-images.githubusercontent.com/2731744/203443493-09dcb46f-ea9b-477f-974c-f77303bafc26.png">

to test: spam the boost button (as though many users were boosting)

**Comment by andrewgodwin** [comment]
This is more a backend bug (it shouldn't let you boost multiple times) as well as a UI bug (the boost event template is not done yet)

**Comment by andrewgodwin** [comment]
I could not reproduce the ability to spam the boost button, but I have fixed the boosted display in 48154fb20e41bf3f4ba2de42de32c3e75d059941
