### ISSUE TITLE
unlisted posts not showing on my public profile for other authenticated users

### ISSUE THREAD

**Issue by whatSocks** [jointakahe/takahe#36]
* user A makes an unlisted post with no mentions
* authenticated user B visits user A's profile and doesn't see the unlisted post
* user B is not following user A

<img width="1407" alt="Screen Shot 2022-11-22 at 6 56 59 PM" src="https://user-images.githubusercontent.com/2731744/203444628-e9b74c48-ad8f-4d31-bd8f-ab5f861b8e1c.png">

**Comment by humrochagf** [comment]
I couldn't reproduce this on my side, both A and B can see unlisted in A profile, did you sync your local copy to the latest commit?

**Comment by andrewgodwin** [comment]
I can't replicate this, and in fact the profile is showing _too many_ posts as it's including mentions-only for me.
