### ISSUE TITLE
"Clear current value" option for profile images not working

### ISSUE THREAD

**Issue by elenners** [jointakahe/takahe#365]
In Settings > Profile > Images, there's an option to wipe the images uploaded for the avatar/profile header. Checking the boxes and saving changes does not remove the images. I attempted it one at a time and both at a time and neither worked.

<img width="610" alt="Screenshot 2023-01-06 at 11 49 11 AM" src="https://user-images.githubusercontent.com/63966511/211069778-6db6cc93-0d05-481c-ac17-73649d053d49.png">

**Comment by andrewgodwin** [comment]
Sorry about that, looks like I just totally forgot to implement that part!
