### ISSUE TITLE
Unfollowing a user does not remove existing posts from the home timeline

### ISSUE THREAD

**Issue by elenners** [jointakahe/takahe#366]
I unfollowed one of my accounts and on other platforms it would result in that account's posts being removed from the home timeline, but they have remained in this case.

<img width="869" alt="Screenshot 2023-01-06 at 11 56 59 AM" src="https://user-images.githubusercontent.com/63966511/211070833-f7955c96-b605-46ce-a02f-11179089d3b9.png">

**Comment by andrewgodwin** [comment]
Yes, this is currently due to the way timelines are constructed - unfollow, disabling boosts from a user, or blocking a domain does not have a retroactive effect. We'll work on this but it's going to be something more medium-term than in the next couple of weeks.
