### ISSUE TITLE
Fix API post/boost IDs

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#380]
Mastodon might return IDs in the API as strings but it intends for them to be sortable by ID (https://docs.joinmastodon.org/api/guidelines/#id) and some clients rely on this particular attribute of them (for example, Tusky), so we need for IDs in the API to behave appropriately.

Currently, we use `1234` for posts and `interaction-1234` for boosts which breaks this.

We have two options:
* Dynamically translate to/from an extended ID format in the API layer
* Move Post and PostInteraction to use a snowflake-style ID that are distinct from each other

**Comment by manfre** [comment]
Snowflake Ids were implemented with https://github.com/jointakahe/takahe/commit/ecec5d6c0a4df7b43c67e1fe4b7503d5962e4426
