### ISSUE TITLE
Cannot click identity metadata on client app

### ISSUE THREAD

**Issue by shuuji3** [jointakahe/takahe#383]
While Mastodon's profile has clickable links, Takahe's profile has no links on URLs. So I cannot visit a website. I tested in Tasky.

<img src="https://user-images.githubusercontent.com/1425259/211254011-31722883-fc84-47f0-aa13-476eb09a0256.png" width="400"><img src="https://user-images.githubusercontent.com/1425259/211254018-cacc6c69-0dae-4cab-9fa5-48b69ff9de47.png" width="400">

Probably we can fix this by returning `<a>` tags in `fields`. Please compare:
- Takahe: https://takahe-dev.shuuji3.xyz/api/v1/accounts/1
- Mastodon: https://mastodon.social/api/v1/accounts/1

**Comment by andrewgodwin** [comment]
Yeah, this just needs us to run those fields through one of our linkifying methods I reckon.

**Comment by shuuji3** [comment]
I see. I'll try applying that method.

**Comment by shuuji3** [comment]
Thanks!
