### ISSUE TITLE
Implement popout menu for small screens

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#399]
To give more screen space for timelines especially on mobile devices
-allow option to remove by instance admin
-or completely removed as default

![takahesidebar](https://user-images.githubusercontent.com/1679025/212032219-4bf6354a-9625-48c6-9e6c-15d057585abd.png)

**Comment by andrewgodwin** [comment]
How would one navigate around the site, then? My eventual plan was to replace it with a popout menu instead (the one you get on sort-of small screens) with a floating menu icon on the top right.

**Comment by okpierre** [comment]
hamburger top navigation (menu top left/right) or bottom row navigation (menu bottom left/right)

![menutopleft](https://user-images.githubusercontent.com/1679025/212133581-44b9d5b5-36a5-47e1-8732-4f96295d203f.png)
![menutopright](https://user-images.githubusercontent.com/1679025/212133609-40839dd0-d2a9-45d8-86a2-43548358a662.png)



![menubottomleft](https://user-images.githubusercontent.com/1679025/212134462-b0db2f70-ef1d-4402-a858-c482b5b8c732.png)

**Comment by andrewgodwin** [comment]
Right, that was the plan already!

**Comment by andrewgodwin** [comment]
Closing as this is all gone now with the timeline UI removal.
