### ISSUE TITLE
improve modularity in nginx config

### ISSUE THREAD

**Issue by foozmeat** [jointakahe/takahe#401]
I'd like to get some of my boilerplate nginx config into the container but the current setup make that difficult. I wonder if Tekahe's config could be created as a set of overrides in `/etc/nginx/conf.d/` so I can manage my own overrides in the same way?

**Comment by andrewgodwin** [comment]
I think that's feasible - it won't be high on my priority list, but I'll happily take a nice PR for it if it's not too many extra files (I'd like it to still be easy to read all together).

**Comment by tabletcorry** [comment]
Would definitely be nice to have more control there. I have a PR that floats on top of main to add my own custom logging format.
