### ISSUE TITLE
Current documentation theme isn't mobile friendly

### ISSUE THREAD

**Issue by simonw** [jointakahe/takahe#42]
Looks like this on my iPhone:

![B2028686-EE88-470D-8496-F893C3FD0866](https://user-images.githubusercontent.com/9599/203827545-c859fe5b-9906-4438-adfd-34c70590c1bb.jpeg)

I think this can be fixed by switching the theme. I'm a fan of Furo here, as used on https://shot-scraper.datasette.io (and others), but there are plenty of other good mobile friendly options.

**Comment by andrewgodwin** [comment]
Yeah, I only switched it away from Alabaster last night so I need to do some more digging into Sphinx themes.

**Comment by TkTech** [comment]
:+1: for Furo, I've used it on all my recent projects. Good light/dark theme support, good support for mobile/small/large/ultrawide screens, extensive (optional) customization options for sidebar and ToC.

**Comment by andrewgodwin** [comment]
Thanks for the recommendation - theme changed!
