### ISSUE TITLE
Unable to edit profile on Tusky for Android

### ISSUE THREAD

**Issue by drewbrew** [jointakahe/takahe#421]
Hey, I've noticed two issues trying to edit my bio on Tusky for Android:

1. The fields I've filled in on the web don't populate in the app (notably the bio field and my custom metadata ![Screenshot_20230115-160601](https://user-images.githubusercontent.com/7773256/212569665-f22bcf2a-e198-478c-9787-038f1bd1eb7e.png)
2. When I try to edit any fields or upload either a profile picture or a cover photo, I get a generic "the upload failed" toast ![Screenshot_20230115-160611](https://user-images.githubusercontent.com/7773256/212569666-38ef5d81-8788-4e4a-9ed4-bfc8ffabd8f0.png)

Steps to replicate:

1. Get an Android device (I'm on a pixel 6 pro running Android 13)
2. Download and install Tusky: https://play.google.com/store/apps/details?id=com.keylesspalace.tusky
3. Log in as a user on takahe.social
4. Open the left sliding menu and tap on "Edit profile"
5. Try to edit any of the fields (display name, bio, custom fields, profile picture, etc)
6. Tap the check icon in the action bar
7. Observe the above failure

**Comment by andrewgodwin** [comment]
Yup, I can see this locally as well. We'll get a fix in shortly!
