### ISSUE TITLE
Remove-IntuneUserPfxCertificate error 403 forbidden

### ISSUE THREAD

**Issue by Azureuser002** [jointakahe/takahe#423]
Remove-IntuneUserPfxCertificate : リモート サーバーがエラーを返しました: (403) 使用不可能
発生場所 行:1 文字:1
+ Remove-IntuneUserPfxCertificate -Userlist "****" ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-IntuneUserPfxCertificate], WebException
    + FullyQualifiedErrorId : System.Net.WebException,Microsoft.Management.Powershell.PFXImport.Cmdlets.RemoveUserPFXC
   ertificate

**Comment by andrewgodwin** [comment]
I don't know what this is but it's not a bug in our code; nothing in our system even gets close to what looks like Windows errors.

**Comment by Azureuser002** [comment]
@andrewgodwin Thank you for your reply.
