### ISSUE TITLE
[documentation] Cloning the repo

### ISSUE THREAD

**Issue by bronikowski** [jointakahe/takahe#43]
In your section on "running locally" you state user should clone the repository with `git clone git@github.com:jointakahe/takahe`, surely you meant the URI to be `https://github.com/jointakahe/takahe/` since the first one needs to be authorized.

**Comment by andrewgodwin** [comment]
That was intended since it's in the contributing documentation, and I was expecting people to then be planning to submit commits back up to a fork. I'll change it for ease of entry though.
