### ISSUE TITLE
Can't use quotes in custom CSS

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#432]
They are apparently escaped too aggressively!

**Comment by hellp** [comment]
The ticket I had already prepared with some notes:

I tried messing with custom CSS, setting it to

```css
body {
  font-family: "Some Nice Font";
}
```

Which ended in the rendered template as:

```html
<style>body {
font-family:&quot;Some Nice Font&quot;;
}</style>
```

I’m not sure how Django’s `safe` filter handles CSS, but maybe it’s enough to add it here:

https://github.com/jointakahe/takahe/blob/bd7076932953c4a77c7cffaee5cb0b760e57850a/templates/base.html#L28

Some hints:

- 2012 post on SO says: “Use |striptags|safe” (https://stackoverflow.com/questions/12854681/what-django-template-filter-to-use-for-embedding-css-in-a-style-tag)

- Current Django docs say: “Warning: Never use |striptags|safe — use bleach.clean()” 

- Bleach docs: “clean() is not safe to use in CSS context.” (https://bleach.readthedocs.io/en/latest/clean.html)

**Comment by TkTech** [comment]
It should be fine to just mark it as safe. There's a reason this is only intended to work for A) yourself or B) by admins. If you want to inject a tag into a page only visible to you, go nuts.
