### ISSUE TITLE
Image preview not available when viewing takahe post from mastodon client

### ISSUE THREAD

**Issue by avolkov** [jointakahe/takahe#434]
The visibility of the post is set to 'public', no content warning is specified.

Expected behaviour -- a user following from mastodon client should be able to see previews of the images posted by a user on a takahe instance.

Current behaviour -- previews are unavailable 

Here's post preview in takahe

![image](https://user-images.githubusercontent.com/648191/212813259-245020df-ed06-402a-b3d6-62d064b145eb.png)

Here's the same preview from mastodon web client

![image](https://user-images.githubusercontent.com/648191/212813218-2c7c7398-03c9-483a-8db8-02495707a833.png)

**Comment by andrewgodwin** [comment]
This works for me on my Mastodon server, so this is not a direct compatibility issue. What Mastodon server is this on and what version is it running?

**Comment by avolkov** [comment]
I’m viewing this from floss.social, running mastodon v4.0.2 I’ll ask serve admin if there are any restrictions for takahe.social.

**Comment by avolkov** [comment]
Ok, this was an issue on floss.social.
Image processing and incoming posts run in the same queue. Incoming post queue was overloaded so this affected image processing.
Posting smaller images later demonstrated that previews are working properly.
