### ISSUE TITLE
Admin configuration for posts in the past

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#435]
Allow for admin configuration for "**_posts in the past_**"

-enable/disable
-allow "posts in the past" within one day/week/month

If new user joins, find a post they like, boost an **old** post, other new users can discover and also interact

As timeline for new instance become busy, this can then be disabled

**Comment by andrewgodwin** [comment]
I don't quite understand what the feature you want here is - you want the ability to turn off the restrictor we have in place that stops old posts from people you follow appearing at the top of the timeline, or something else?

**Comment by okpierre** [comment]
Sorry read your 0.7 release blog post about "_Posts From The Past_" and should've referenced it

### Here's the section this issue is referring to:

"We did make a change to our timeline builder so it doesn't add things to the Home timeline if they were **received more than a day** after they were published"

Does Takahe currently have admin setting to configure this?

<details>
  <summary>reference</summary>
<img src="https://user-images.githubusercontent.com/1679025/213007001-102836fa-4642-4d75-91c7-3444d411dead.png">
</details>

**Comment by andrewgodwin** [comment]
No, and I don't quite see why you'd want to, as it's very confusing for users to see a normal post from 30 days ago at the top of their timeline. Note this doesn't affect boosts of old posts - those appear just fine - it's the actual plain posts themselves.

**Comment by okpierre** [comment]
Got it. Thought it meant the home timeline would not receive anything old. Closing.
