### ISSUE TITLE
Setup script

### ISSUE THREAD

**Issue by no-gravity** [jointakahe/takahe#44]
It would be great to have a setup script that turns a fresh Debian installation into a running Takahe instance.

Optimally without using Docker.

An example of the kind of setup script I mean can be seen in the Django script here:

https://github.com/no-gravity/web_app_from_scratch

**Comment by andrewgodwin** [comment]
So, I am deliberately avoiding offering a non-Docker install path that is supported right now as it leads to a lot of support burden with different OS package versions and the like!

If I revisit that stance in the future, this would be a good idea though.

**Comment by no-gravity** [comment]
I don't see how an install script that targets a specific Debian version would introduce more issues with "OS package versions and the like" than a dockerfile. Both target a specific base.

In fact, I usually specify the debian:11-slim Docker image as the target for such an install script.

**Comment by andrewgodwin** [comment]
I know, but it's just a case of maintainer preference right now - until things are more settled and there's more full-time committers, I'd rather not have to worry about maintaining a setup script as well right now.

It's a standard Django project, though, so any Django project install guide is probably quite transferable.
