### ISSUE TITLE
Account deletion

### ISSUE THREAD

**Issue by EwanCroft** [jointakahe/takahe#440]
I'm not sure if I'm just being stupid, but there doesn't seem to be any way to delete an account from [https://takahe.social](takahē).

If anyone has a way to do this, please let me know either through Mastodon, I'm here: [https://mstdn.social/@EwanCroft](mastodon) or here on GitHub.

**Comment by andrewgodwin** [comment]
@EwanCroft User-initiated account deletion is not in yet. If you want your account deleted, email contact@jointakahe.org from the email address you signed up from and we'll confirm it's you and then do it for you!

**Comment by EwanCroft** [comment]
@andrewgodwin Done! thank you for the reply
