### ISSUE TITLE
Difficult to see header icons in light mode

### ISSUE THREAD

**Issue by shuuji3** [jointakahe/takahe#446]
The combination of dark color icons and dark background makes it difficult to see.

## Current
<img width="692" alt="Screenshot 2023-01-19 at 18 42 38" src="https://user-images.githubusercontent.com/1425259/213409118-5bdb56b6-f917-47a3-b10b-cdb0724e63a4.png">

### Option 1
<img width="674" alt="Screenshot 2023-01-19 at 18 45 05" src="https://user-images.githubusercontent.com/1425259/213409834-0d9380b8-033a-49b7-9cbd-a2098313fce5.png">

### Option 2
<img width="665" alt="Screenshot 2023-01-19 at 18 43 03" src="https://user-images.githubusercontent.com/1425259/213409840-bea15b75-3c9b-4b44-b575-1020a3b71f73.png">

**Comment by andrewgodwin** [comment]
I think option 1 still looks the best here.

**Comment by shuuji3** [comment]
OK!👍🏻  Then, I'll make a PR to update the style for Option 1.
