### ISSUE TITLE
Hashtags on our posts served from Mastodon appear as normal links

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#448]
Hashtags work fine in our web UI, on clients talking to our API, and on the Mastodon Web UI, but do not work properly on clients talking to the proper Mastodon API and retrieving our posts.

Something about our hashtags is making it through Mastodon's internal storage out into their client API, and I have no idea what.

**Comment by manfre** [comment]
Most likely a result of preferring the href when stripping the post content down to plaintext.

**Comment by andrewgodwin** [comment]
It's not that - it's something about how Mastodon presents hashtags to clients versus in their UI (where it totally works).

I verified that Elk also gets it wrong when seeing one of our posts on a Mastodon server, so it's presumably something we have to add onto our HTML that mastodon will then pass through and not rewrite?

**Comment by andrewgodwin** [comment]
OK, I've tried adding `rel=tag` and the classes, and they don't make a difference. Someone is going to have to go into the source code of a client and figure out what's happening and why they disagree with the Mastodon web UI.

**Comment by glassresistor** [comment]
this looks like it might be where elk decides if content is a hashtag
https://github.com/elk-zone/elk/blob/359cc4935b5dee59743add577a540b04a32f643c/composables/content-parse.ts#L21

**Comment by andrewgodwin** [comment]
I don't think so - that just looks like a general list of classes to allow through into the HTML. I'd be expecting something to go looking in the `tags` part of the API response, maybe.

**Comment by humrochagf** [comment]
Following up on the question in the MR @andrewgodwin I just ran some more tests with my instances to validate the boost case and it seems that it's all fine, we can close this issue, unless someone has found a corner case.

**Comment by andrewgodwin** [comment]
This issue is specifically about them not working in certain API clients - is that where you checked?

**Comment by humrochagf** [comment]
Tested on tusky and now on elk, both receiving boost and posts from takahe accounts to Mastodon (fosstodon) ones.
Looking from takahe side it will not display anything since we don't have preview card feature implemented.

![Screenshot from 2023-02-20 12-11-36](https://user-images.githubusercontent.com/1223625/220167670-c46ecba4-2af2-47d6-bde7-f9939c2a1fcc.png)

**Comment by humrochagf** [comment]
Ah, and Mastodon frontend interface is also working

**Comment by andrewgodwin** [comment]
Lovely! Thank you for the through testing!
