### ISSUE TITLE
[Discussion] Should we ensure pypy compatibility?

### ISSUE THREAD

**Issue by mochaaP** [jointakahe/takahe#45]
pypy is a dialect of Python, supporting most CPython features while being times faster by utilizing Just-In-Time compilation.

Do we have incompatible dependencies or technique that's unavailable on pypy? If yes, is the performance boost big enough for the deal?

**Comment by andrewgodwin** [comment]
Ah yes, I would like to ensure that if possible - I use pypy for a lot of personal compute-heavy projects.

My main worry here would be things like the `crytography` module and `pillow`, but I believe that's all working at this point.

**Comment by mochaaP** [comment]
iirc some version of `cryptography` has a dependency on `pyo3`, which could lead to a compilation error because `pyo3` does not support some certain functions for pypy.

**Comment by TkTech** [comment]
psycopg2 is incompatible with pypy, so you can use the psycopg-cffi alternative (which is usable but out of date), or you can use psycopg3, but you'll need to include their demonstration django driver, which I wouldn't consider stable yet.

**Comment by andrewgodwin** [comment]
Ah, that's sad. I think then, for now, we'll shelve this as an official thing being pursued and just keep our eye on it for when psycopg3 is more ready.

**Comment by TkTech** [comment]
Discussion for tracking:

- https://www.psycopg.org/articles/2021/08/02/psycopg3-django-driver/
- https://github.com/django/django/compare/stable/3.2.x...dvarrazzo:psycopg3-support (django changset required)
- https://github.com/dvarrazzo/django-psycopg3-backend (django driver)
