### ISSUE TITLE
Underscore in Subdomains for service domain

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#450]
When creating a new Domain with a service domain which includes an underscore in the subdomain, Takahe says, that it doesn't look like a domain:
![](https://mws.bka.li/sharex/2023/01/firefox_20230119_205948.png)

When replacing the underscore with a simple one, everything works as expected.

**Comment by andrewgodwin** [comment]
Turns out they're not actually valid in domain names according to RFC 1035, so we'll keep this validation as is.
