### ISSUE TITLE
Dual pane for user to domain selector

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#452]
Currently, the selection is not really clear, at least to me, if a user is selected and if not, and how to deselect a user, ...
![](https://mws.bka.li/sharex/2023/01/firefox_20230119_210858.png)

Would it be possible, to get a two pane list, including a search with left existing users and right assigned users? Maybe then the + would make more sense too, right?
I thought about something like this:
![](https://mws.bka.li/sharex/2023/01/users.png)

**Comment by andrewgodwin** [comment]
That's the django admin and we can't change much about it except make it a raw_id field which is worse - I'm going to close this one as the real fix is #451.
