### ISSUE TITLE
Disappearing follower

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#456]
After setting up new Domains to my Takahe install, I saw, that external follows will just disappear after a while.

![Screenshot from 2023-01-20 09-23-22](https://user-images.githubusercontent.com/1553902/213649647-0ffbd2ec-9dc2-4fb5-a10f-61c44642bfd1.png)

I tried this several times:

* Following `@support@bka.li` with my `@kromonos@fosstodon.org` account
    * The follow appears normally on both sides
* Switching identities, checking messages, reply to some posts. Usual stuff
* Switching back to the `@support@bka.li` account again and the follow is gone in Takahe, but still set on Fosstodon
* Unfollow and refollow from Fosstodon throws an exception in the logs, but then we can start from the beginning

![Screenshot from 2023-01-20 09-16-16](https://user-images.githubusercontent.com/1553902/213650254-b061c455-6c83-47d8-9402-eaf397342526.png)

**Comment by andrewgodwin** [comment]
Follows are only undone under a very small set of circumstances - you have to unfollow, or a block has to be put in place against the user or remote domain - and then it takes a further 24 hours for it to remove from the database as your error shows.

How long was the gap here between following and then it vanishing?

**Comment by andrewgodwin** [comment]
OK, that's super short then.

Are you able to go into the admin and see if there is a `Follow` object set up between the two accounts still? It should be near the top if it's recent.

**Comment by andrewgodwin** [comment]
OK, so the problem is the UI not showing them rather than the follow not existing, interesting. Could you screenshot the follow object for me?

**Comment by andrewgodwin** [comment]
Yes, that also indicates that it thinks it doesn't exist, which is why I want to look closely at the data in a screenshot!

No rush, get to it when you can.

**Comment by andrewgodwin** [comment]
Ahh, so it's not a bug?

**Comment by andrewgodwin** [comment]
5 minuteś is what we often use for internal state timers so that suggests that something might be happening with Stator. Can you get the stator logs during this period and see if there's anything about the disappearing Follow?

**Comment by andrewgodwin** [comment]
It feels like an unfollow request is stuck, or something - I'd maybe take a look at your InboxMessages too and see if there's anything related in there (you can stick the actor URI for that account in the admin search field to narrow things down)
