### ISSUE TITLE
Explain the choice of name please

### ISSUE THREAD

**Issue by eliotb** [jointakahe/takahe#46]
It isn't in the readme or in the blogs AFAICS.

Take a look at https://maoridictionary.co.nz/

takahē

1. (noun) South Island takahē, notornis, Porphyrio hochstetteri - rare, flightless endemic bird that looks like a large pūkeko with a greenish back. Lives in tussock grasslands of Fiordland.

(Te Pihinga Textbook (Ed. 2): 108;) 

2. (verb) to go wrong, come to nothing.

Nō muri mai ka hoatu he tūru mōna i te Kaunihera Ture, engari i takahē noa (TTR 1994:199). / Later he was given a seat in the Legislative Council, but it came to nothing.

**Comment by andrewgodwin** [comment]
It is named after the bird, _Porphyrio hochstetteri_. Mostly because I like New Zealand's very specialist endemic birds, and a little bit because it was a bird that was thought extinct but actually survived, and I like that aspect of the story as it applies to social networking.

**Comment by andrewgodwin** [comment]
Further note - I've put a mention on the About page calling out this specifically, along with a link to donate to the Takahē conservation efforts if anyone is interested: https://jointakahe.org/about/
