### ISSUE TITLE
Maximum post length does not match counter

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#460]
Here's how it looks on v0.7

![takahe-maximum-post-length](https://user-images.githubusercontent.com/1679025/213765181-a56f2e21-9e61-490a-b0db-283ec3b0c023.png)

**Comment by andrewgodwin** [comment]
Ooh, fascinating, and I can't even see any emoji or other unicode that might do this. I'll see if I can replicate it later.

**Comment by shuuji3** [comment]
Hmm, it seems like the count of a newline is different between Hyperscript and Python. Every time I delete one character and add one newline, Python counts one more character.

**Comment by andrewgodwin** [comment]
It might be that one is `/r/n` and one is `/n`. The emoji count may also be off.

**Comment by shuuji3** [comment]
Your assumption was right! `\n` is normalized as `\r\n` when counting in Python.

<img width="705" alt="Screenshot 2023-01-28 at 1 23 01" src="https://user-images.githubusercontent.com/1425259/215139001-b2bfcb1f-b8cd-4ab5-a917-7630665e9e1e.png">

logging:

```
docker-web-1  | length: 501
docker-web-1  | repr(test): 'takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, takahē, newline=>\r\n<='
```
