### ISSUE TITLE
Add upgrade instructions in documentation

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#461]
A quick search using 'update' and 'upgrade' in the documentation located here
`https://docs.jointakahe.org/en/latest/installation/`

yields only notes about release updates

For beginners and those new to Takahe, it would help to have instructions on how to upgrade from one version to the next

For example: upgrade from v6.x to v7.x or v7.x to the next

Maybe something like Mastodon?
`https://docs.joinmastodon.org/admin/upgrading/`

**Comment by andrewgodwin** [comment]
Yes, it would be good to have a section for this, though it will just be:

- Bump the docker image version
- Run migrations
