### ISSUE TITLE
emoji shortcode instead of image in name and bio

### ISSUE THREAD

**Issue by kromonos** [jointakahe/takahe#468]
I first had a GIF in the name
![](https://mws.bka.li/sharex/2023/01/chrome_20230122_000706.png)

Because I thought, it could be because of the GIF, so I tried with a PNG
![](https://mws.bka.li/sharex/2023/01/chrome_20230122_000917.png)

Same goes with bio:
![](https://mws.bka.li/sharex/2023/01/firefox_20230122_001424.png)

**Comment by andrewgodwin** [comment]
To be specific, you are saying that the emoji is appearing on Takahē and not on Mastodon/other servers?

**Comment by andrewgodwin** [comment]
Should be fixed by 1670c922693dee6e64a3d076c5f09be11191a20e

**Comment by andrewgodwin** [comment]
Oh, right, profile updates are different. I'll get that fixed!

**Comment by andrewgodwin** [comment]
OK, that should also be fixed
