### ISSUE TITLE
Confusing setup option

### ISSUE THREAD

**Issue by llimllib** [jointakahe/takahe#469]
After setting up a server, then getting to "config", you're presented with:

```
DEFAULT
If this is the default option for new identities
```

(Screenshot: <img width="399" alt="image" src="https://user-images.githubusercontent.com/7150/214148329-89f84667-b043-4e49-956e-849d071b3cd7.png">)

But I have no idea what "this" refers to in this circumstance. What default am I setting here?

**Comment by llimllib** [comment]
- After going through more config, I think the answer is: "this domain"
- I want to have a domain that is private - I will create all identities for now. But when I added a private domain:
    - it didn't show up as an option for creating my identity
    - it won't let me select it as the default domain?

Clearly I'm misunderstanding what these options mean in concert

**Comment by andrewgodwin** [comment]
Private domains currently need extra manual configuration via the admin to assign them to users - see #451. You can't make them the default domain for that reason - the default domain has to be one that's open to any user on the server.

I'll make that wording a little clearer, though.
