### ISSUE TITLE
Elk shows duplicated mention links for some status

### ISSUE THREAD

**Issue by shuuji3** [jointakahe/takahe#479]
(This issue was already reported at elk-zone/elk#1336. But I create a new issue here since it seems that it's the issue of takahē API response.)

## Using takahe.social account

Example status has double `@mension` links: https://elk.zone/takahe.social/@liaizon@wake.st/139038048149229824

Elk is fetching actual data from https://takahe.social/api/v1/statuses/139038048149229824 and it returns the following JSON:

```json
{
  "id": "139038048149229824",
  "uri": "https://social.wake.st/users/liaizon/statuses/109718382338430403",
  ...
  "content": "<p>I made cute avatars for my Takah\u0113 (<a href=\"https://takiverse.tk/@takiverse/\" class=\"u-url mention\" rel=\"nofollow\"></a><a href=\"https://takiverse.tk/@takiverse/\">@takiverse</a>) and GoToSocial (<a href=\"https://xn--4lj0cra7d.todz.ynh.fr/@liaizon\" class=\"u-url mention\" rel=\"nofollow\">@liaizon@\u2d30\u2d63\u2d53\u2d4d.todz.ynh.fr</a>) test accounts!</p>",
  ...
  "text": "<p>I made cute avatars for my Takah\u0113 (<a href=\"https://takiverse.tk/@takiverse/\" class=\"u-url mention\" rel=\"nofollow\"></a><a href=\"https://takiverse.tk/@takiverse/\">@takiverse</a>) and GoToSocial (<a href=\"https://xn--4lj0cra7d.todz.ynh.fr/@liaizon\" class=\"u-url mention\" rel=\"nofollow\">@liaizon@\u2d30\u2d63\u2d53\u2d4d.todz.ynh.fr</a>) test accounts!</p>",
  ...
}
```

as you can see, it has two `<a>` tags. The first one is empty and the second one has `@user` text but no `class="u-url mention" rel="nofollow"` attributes.

## Using mastodon.social account

Same status but fetched from mastodon.social account: https://elk.zone/mastodon.social/@liaizon@wake.st/109718383196875476

API endpoint for the status: https://mastodon.social/api/v1/statuses/109718383196875476

```json
{
  ...
  "content": "<p>I made cute avatars for my Takahē (<span class=\"h-card\"><a href=\"https://takiverse.tk/@takiverse/\" class=\"u-url mention\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">@<span>takiverse</span></a></span>) and GoToSocial (<span class=\"h-card\"><a href=\"https://xn--4lj0cra7d.todz.ynh.fr/@liaizon\" class=\"u-url mention\" rel=\"nofollow noopener noreferrer\" target=\"_blank\">@<span>liaizon@ⴰⵣⵓⵍ.todz.ynh.fr</span></a></span>) test accounts!</p>"
  ...
}
```

This `content` difference seems the cause of the duplication. I'm not sure but I suspect that the HTML string was sanitized twice.

**Comment by andrewgodwin** [comment]
Oh, fascinating. Thanks for figuring this out - interesting they're the only client who ignores link contents! I'll see if I can figure it out.

**Comment by andrewgodwin** [comment]
OK, it looks like our change to preserve links has been preserving incoming mention links and then adding our own around them (which bleach corrects to be next to).

I'm gonna have to rewrite the entire HTML parser for this one, I think!

**Comment by andrewgodwin** [comment]
In what is maybe the largest diff yet for an apparently small bug, I have rewritten the HTML parser in https://github.com/jointakahe/takahe/commit/a6922cb9d6b98f958a230636c489fd9f4c96bd5b and it has fixed the double link issue.

**Comment by shuuji3** [comment]
Great, thank you!
