### ISSUE TITLE
Using "media_ids[]" as key for media_ids is not adding media to status via API

### ISSUE THREAD

**Issue by marvin8** [jointakahe/takahe#490]
My app is posting status with media. Through testing it seems that Takahe is not recognizing `media_ids[]` as key in JSON data submitted to `/api/v1/statuses` endpoint. 

Sending the following JSON results in no attachments added to the post:
```
{
    "status": "capybara #capybara https://redd.it/10rwhmv",
    "visibility": "unlisted",
    "sensitive": true,
    "media_ids[]": [
        "19456"
    ]
}
```

This is contrary to the [Mastodon API definition](https://docs.joinmastodon.org/methods/statuses/#form-data-parameters)

As a workaround i am also adding the same media ids with a JSON key of `media_ids` as below which seems to work.

```
{
    "status": "capybara #capybara https://redd.it/10rwhmv",
    "visibility": "unlisted",
    "sensitive": true,
    "media_ids[]": [
        "19456"
    ],
    "media_ids": [
        "19456"
    ]
}
```

**Comment by andrewgodwin** [comment]
Interesting - most clients we've tested this with use formdata rather than JSON bodies for this, so we missed that.

Are you sure the Mastodon key is `media_ids[]` in JSON body mode? https://docs.joinmastodon.org/client/intro/#array would indicate otherwise, which is why I coded it like this.

**Comment by marvin8** [comment]
I've been using `media_ids[]` key with Mastdon (botsin.space) and Pleroma (cawfee.club) server instances for quite some time successfully. While you're interpretation of the Mastodon doc might be correct, from my experience it certainly is different to how the servers react.

I'll do some more testing on my end...

**Comment by andrewgodwin** [comment]
It certainly would not be the first time the Mastodon API docs don't match the implementation! I suspect it might accept both arrangements.

Either way, if they support it, so should we. I'll need to redo our API parser layer a bit first - the way Mastodon mangles together JSON, formdata, and query params is taking a bit of effort to convince Django to do.

**Comment by marvin8** [comment]
So I changed my code back to using formdata as below:
```
        form_data = aiohttp.FormData()
        form_data.add_field(name="status", value=status)
        form_data.add_field(name="visibility", value=visibility)
        form_data.add_field(name="sensitive", value=sensitive)
        if media_ids:
            form_data.add_field(name="media_ids[]", value=media_ids)
        if spoiler_text:
            form_data.add_field(name="spoiler_text", value=spoiler_text)

        async with self.session.post(
            url=url,
            headers=headers,
            data=form_data,
        ) as response:
```

and again I get the media not attached to the post (https://takahe.social/@capybara/posts/144139249467906208/)

Looking at my debug output, I can see the media has been uploaded successfully to Takahe. `/api/v1/media` responded with: 
```
{
    "id": "19584",
    "type": "image",
    "url": "https://storage.googleapis.com/takahe-social/attachments/2023/2/3/6LuvUQxQFTkS7ijzMrbTgWYaqA0.webp",
    [...]
}
```

PS: trying to add the media_ids field without `[]` to the formdata errors out, so I am assuming formdata.addField parses the name to decided if the field is an array or not.

**Comment by andrewgodwin** [comment]
I just looked at the code and it appears I misspoke earlier - we seem to only accept media in the JSON body form without the square brackets. I think I was thinking of media uploads themselves always being multipart data instead.

Thus, the workaround in your first message would be best for now; I'll get our stuff fixed up so that this works across all versions.

**Comment by andrewgodwin** [comment]
This should now be fixed with the new API framework we have - it's both checked into `main` and up on takahe.social. If you could verify it would be appreciated!

**Comment by marvin8** [comment]
Awesome... just did a quick test without my workaround.

I am happy to confirm that I no longer need the workaround and using "media_ids[]" works same as on Mastodon and Pleroma instances I interact with.

Thank you
