### ISSUE TITLE
Emojis in Mastodon api are case sensitive

### ISSUE THREAD

**Issue by humrochagf** [jointakahe/takahe#492]
All emoji ingested by takahe stores its shortcode as lowercase, but Mastodon expects them to be case sensitive, so if an emoji has an uppercase letter, it isn't displayed by neither, mastodon interface or clients like tusky. Even takahe interface can't display them properly.

**Comment by humrochagf** [comment]
For this one, I can see two options:

- Keep storing them as lowercase but return  them with the requested casing.
- Start storing them with the original casing (this option will create some emoji duplication due to the already stored ones, but its not the end of the world)

**Comment by andrewgodwin** [comment]
I just tested and it's not even that Mastodon is case-preserving (like usernames), it's truly case-sensitive - `:shortcode:` and `:ShortCode:` can both be completely different emoji. What an odd design choice.

Anyway, yes, we have to support it.
