### ISSUE TITLE
Developer API keys / Authorised applications

### ISSUE THREAD

**Issue by chris-y** [jointakahe/takahe#498]
Mastodon has a UI for adding applications, setting permissions, and providing the client key/secret/access token. I find this incredibly useful for personal apps/bots that don't need the oauth flow. Please can this be added to Takahe along with the ability to see and revoke permissions for current authorised apps.

**Comment by andrewgodwin** [comment]
Yup, the whole applications UI does need writing, and I agree an easy way to make personal keys should be in there.

**Comment by andrewgodwin** [comment]
This has been merged in as part of the big refactor - you can see what apps are authd, revoke their access, and make a personal access token and view it.
