### ISSUE TITLE
Why does nginx have hardcoded external DNS resolver?

### ISSUE THREAD

**Issue by osmaa** [jointakahe/takahe#501]
It took me longer than I care to admit to understand that the proxy timed out because it was trying to resolve addresses using

`resolver 9.9.9.9 149.112.112.112 ipv6=off`

while my environment was firewalled to the max, and external DNS was not among permitted services. Regular DNS was working just fine, because it was accessing a network-local resolver..

Opening the firewall for UDP/53 and TCP/53 of course worked around this, but why would the local resolver be bypassed? And why prevent IPv6?

**Comment by andrewgodwin** [comment]
Nginx cannot use the system resolver, and needs a hardcoded one in order to do DNS lookups. If you can figure out a way to stop this and make it inherit the system configuration, do let me know.

**Comment by osmaa** [comment]
https://trac.nginx.org/nginx/ticket/658#comment:5 copied below

Heres a workaround for people using Docker.

```
export NAMESERVER=`cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}' | tr '\n' ' '`
```

What this does is take all the nameserver entries from /etc/resolv.conf and print them in a line, so you can use them with nginx's resolver directive.

Your Dockerfile will need to have a custom script for the entrypoint that generates the config file and then starts nginx.

Lets say you have a file called nginx.conf.template that looks something like:

```
...snip...
http {
  server {

    resolver $NAMESERVER valid=10s;

    ...snip....  
    }
  }
}
```

Your startup script can then use the envsubst program to generate an nginx.conf and then start nginx. eg:

```
#!/bin/bash
if [ "$NAMESERVER" == "" ]; then
	export NAMESERVER=`cat /etc/resolv.conf | grep "nameserver" | awk '{print $2}' | tr '\n' ' '`
fi

echo "Nameserver is: $NAMESERVER"

echo "Copying nginx config"
envsubst '$NAMESERVER' < /nginx.conf.template > /nginx.conf

echo "Using nginx config:"
cat /nginx.conf

echo "Starting nginx"
nginx -c /nginx.conf -g "daemon off;"
```

**Comment by andrewgodwin** [comment]
Thanks for that - I've now implemented that approach in our Dockerfile.
