### ISSUE TITLE
Manage group role and permissions

### ISSUE THREAD

**Issue by okpierre** [jointakahe/takahe#503]
example

group role: tier1 / tier2 / tier3

all users start in tier1 - limited permissions

member for at least **x** months and have **xx** posts
user now in tier2 and have yyy permissions

member for at least **xx** months and have **xxx** posts
user now in tier3 and have yyy permissions

![takahepermissions](https://user-images.githubusercontent.com/1679025/217332036-5c48dc3a-9b90-4c9c-b066-1d50f2c31609.png)

**Comment by andrewgodwin** [comment]
The permissions dialog you have there is the built-in Django one that we are not using - I will figure out a way to hide it at some point.

I do not have any plans on doing a tiering system, mostly because I don't know what would unlock progressively!
