### ISSUE TITLE
Django 4.2 support

### ISSUE THREAD

**Issue by manfre** [jointakahe/takahe#504]
Currently blocked by [pytest-django PR 1044](https://github.com/pytest-dev/pytest-django/pull/1044), which is blocked by [django-configurations PR 349](https://github.com/jazzband/django-configurations/pull/349)

**Comment by pauloxnet** [comment]
I've just reviewed the `django-configuration` PR.

**Comment by pauloxnet** [comment]
I've just merge the `django-configuration` [PR 349](https://github.com/jazzband/django-configurations/pull/349) , I hope that this will unblock this issue.

**Comment by pauloxnet** [comment]
We've released django-configuration 2.4.1 on puoi si you can now test it.

**Comment by pauloxnet** [comment]
Also [pytest-django](https://github.com/pytest-dev/pytest-django) has been updated for Django 4.2, so this issue is not blocked anymore.

**Comment by manfre** [comment]
Opened PR https://github.com/jointakahe/takahe/pull/555 and running on https://manfre.net

**Comment by andrewgodwin** [comment]
PR merged!
