### ISSUE TITLE
When loading a new page of posts, the paging is off if new posts have arrived since I last loaded a new page

### ISSUE THREAD

**Issue by rimu** [jointakahe/takahe#518]
This is most obvious on the Federated timeline because it moves quickest.

Usually the last 1 or two posts from the previous page are duplicated at the top of the next page.

e.g. the top two posts here were at the end of a page. Then I loaded the next page by scrolling down and two more identical posts were shown. ![duplicated content](https://user-images.githubusercontent.com/3310831/220465017-af5efb9b-74b4-4900-803d-c0cc1d7a0ad7.png)

**Comment by andrewgodwin** [comment]
Ah yes, this will be because we use simple offset pagination rather than the "after X" style that we should be using now we use snowflake IDs.

**Comment by andrewgodwin** [comment]
Closing as the timeline web UI has been removed, and this was solved separately for the API.
