### ISSUE TITLE
Tighten up the CSS a little

### ISSUE THREAD

**Issue by rimu** [jointakahe/takahe#523]
Here's the CSS I'm using ala myspace (great feature!) to create a more mastondon-like UI. The maintainer(s) may choose to adopt some of it into the core app, or perhaps it will just sit here for users to snaffle for their own use.

Attached are some screenshots of how it looks.

```
body {
    font-size: 16px;
    font-family: "Atkinson HyperLegible", system-ui, -apple-system, BlinkMacSystemFont, Segoe UI, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;
    line-height: 1.35;
}

#main-content {
    padding: 0;
}

.post {
    box-shadow: none;
    margin-bottom: 0;
    border-bottom: solid 1px var(--color-text-dull);
}

.post .content {
    max-width: 665px;
}

.post .content a {
    word-break: inherit;
}

.boost-banner {
    background-color: var(--color-bg-box);
    padding-top: 10px;
    padding-left: 14px;
    padding-right: 12px;
    padding-bottom: 0;
}

form .buttons {
    padding-right: 15px;
}

form label {
    font-size: 115%;
    text-transform: inherit;
}

fieldset legend {
    left: 0;
}
```

On mobile:

![new_mobile](https://user-images.githubusercontent.com/3310831/221323612-ad1a989a-d71b-4ad6-8f3c-c8d7dac495eb.png)

Desktop:

![new_desktop](https://user-images.githubusercontent.com/3310831/221323615-900eee18-b936-4bde-abbb-77be92c1a08c.png)

**Comment by andrewgodwin** [comment]
Thanks for leaving this here, but I'm not interested in reducing the spacing much further at this point - at some point, I want to revisit the whole layout and see if we can get it tighter without losing readability, but right now it's at a sweet spot for me personally (and unfortunately, that is the bar by which I currently judge the layout!)

**Comment by rimu** [comment]
Totally fair enough.

Maybe one day there will be a takahe css theme garden for sharing snippets like this...
