### ISSUE TITLE
Crash when viewing a post

### ISSUE THREAD

**Issue by rimu** [jointakahe/takahe#527]
E.g. when going to https://takahe.social/@carnage4life@mas.to/posts/152416748228892048/ nothing happens for a while and then eventually a " bad gateway" message is displayed.

![Screenshot_20230226-120851](https://user-images.githubusercontent.com/3310831/221383766-b960f151-354d-46d7-b971-bcd31fdacc40.png)

This only started happening recently, after load increased by people importing their followers. Could be related. Also it only happens with posts which have (lots of?) replies.

**Comment by andrewgodwin** [comment]
It's only that specific post, so it's likely something in there is triggering it. I'm currently on vacation in Australia, so I'll try to download this post onto my local test server once I'm back home.

**Comment by rimu** [comment]
No, if I click 'View post and replies' on posts that look popular (skipping those that obviously won't trigger the issue) then it happens about 25% of the time. It's pretty reliable.

Here are some more:

https://takahe.social/@molly0xfff@hachyderm.io/posts/152560707896168424/
https://takahe.social/@baekdal@mastodon.social/posts/152554719357278016/
https://takahe.social/@dangillmor@mastodon.social/posts/152527338538858880/
https://takahe.social/@parkermolloy@masto.ai/posts/152010227831763936/

**Comment by andrewgodwin** [comment]
Now I'm back from Aus, I have dug in a little more and found that those posts are causing the entire thread to raise SystemExit. I don't quite know why yet.

**Comment by andrewgodwin** [comment]
OK, traced this down to there being no index on Post.in_reply_to - calculating post reply counts was astonishingly slow. It's still not speedy to display, but there's some general performance improvements I'm going to be making to all pages, so closing this with https://github.com/jointakahe/takahe/commit/afc94f63135a80bef49c9501f4b6ae0c46d67f53 as the designated fix.

**Comment by rimu** [comment]
Nice one!

I wonder if adding a number_of_replies field to the post might be even faster than adding an index. Certainly the index is easier and requires no upkeep, tho.

**Comment by andrewgodwin** [comment]
We already have a general stats field for post counts - it's used for likes and boosts already, just needs a bit of code to add replies.
