### ISSUE TITLE
Profile pics sometimes fail to load

### ISSUE THREAD

**Issue by rimu** [jointakahe/takahe#536]
Here is an example, with JS error displayed in browser console. I'm using Firefox on Linux.

![no profile pic - desktop](https://user-images.githubusercontent.com/3310831/224459782-30015a80-8cd9-41f3-b0bc-1617ac5c973e.png)

Same thing happens on Firefox on Android: 
![Screenshot_20230311-151359](https://user-images.githubusercontent.com/3310831/224459797-a40455c1-750e-417d-8305-1c8162e56764.png)

FYI here is Dave Lane's profile pic: https://mastodon.nzoss.nz/system/accounts/avatars/000/000/001/original/78bd7405894e802f.png. Maybe there is something odd about the file. 

Another profile pic that failed to load was [this guy](https://mastodon.nzoss.nz/@dn) and [his profile pic is this](https://mastodon.nzoss.nz/system/accounts/avatars/000/160/278/original/16681afba75edca1.jpeg).

**Comment by rimu** [comment]
On Chromium there is an additional message in the JS Console, about how retrieving an image returned 403. It seems to refer to the image in the takahe cache/proxy, not to the mastodon-hosted original.

![no profile pic - chrome](https://user-images.githubusercontent.com/3310831/224460069-6a3e1833-5ad1-49be-9ac9-88cb7646406c.png)

**Comment by rimu** [comment]
Here are 3 more, these ones are not on mastodon.nzoss.nz:

![another](https://user-images.githubusercontent.com/3310831/224460602-5bfe1cdf-0c48-43ee-bf40-cd3218926158.png)
![and another](https://user-images.githubusercontent.com/3310831/224460597-e1fc0d57-e666-4185-b736-e0ba97b1c3e2.png)
![third one](https://user-images.githubusercontent.com/3310831/224460594-657cbb0c-e419-4f49-b543-6f95ef3d524b.png)

**Comment by andrewgodwin** [comment]
Interestingly, it works on my development copy, so I'm not quite sure what's going on here. It's possible that the other servers are blocking our image proxy; I'll try adjusting the nginx user agent to see if that helps.

**Comment by andrewgodwin** [comment]
Looks like it was us passing through too many headers - should be fixed now.
