### ISSUE TITLE
Username linking in (some) posts conflates multiple names with the same left-hand-side

### ISSUE THREAD

**Issue by kvibber** [jointakahe/takahe#546]
Under some circumstances, if a post lists multiple users who have the same username at different servers, *all* of them are linked to the last profile listed when viewed in Takahe.

I made a list of a bunch of my own accounts in a GoToSocial post. When viewed through Takahe, all three KelsonV usernames are linked to gts.keysmash.xyz instead of the first two being Wandering.shop and Pixelfed.social. Both ktv usernames are linked to mycrowd.ca instead of the first one to takahe.social.

Original post on GoToSocial: https://gts.keysmash.xyz/@kelsonv/statuses/01GW3RFPQ4E6ZTE31VME9Q83WG
Viewed through Takahe: https://takahe.social/@kelsonv@gts.keysmash.xyz/posts/161221316797810360/

Akkoma and Mastodon link to the correct profiles when displaying the post.

Composing in Takahe or Mastodon didn't trigger the problem. Composing another test message in GoToSocial did. (Though I had to make sure I mentioned my Tahake username in the post, because following GTS from Takahe doesn't work yet)

This may be specific to GoToSocial and Takahe interacting with each other.

**Comment by andrewgodwin** [comment]
Fix is deployed on takahe.social and looks good now - thanks for the report!
