### ISSUE TITLE
/api/v1/accounts/familiar_followers via Ivory crashes web process

### ISSUE THREAD

**Issue by chdorner** [jointakahe/takahe#547]
Not sure if I should open an issue on the hatchway repo or here.

I tracked this down to an unhandled pydantic exception inside hatchway which ends up crashing the Django web worker.
Ivory is sending the `id` parameter, not as a list like [documented in the Mastodon API](https://docs.joinmastodon.org/methods/accounts/#familiar_followers), but just as a string, i.e.: `/api/v1/accounts/familiar_followers?id=158915328448909978`, instead of `/api/v1/accounts/familiar_followers?id[]=158915328448909978`

It happens here: https://github.com/andrewgodwin/django-hatchway/blob/82713b549a93e1425a5b35e95765ad2f555f1300/hatchway/view.py#L283

**Comment by andrewgodwin** [comment]
Oh, that's very fun. It's probably correct of Pydantic to bail, so I need to fix hatchway to not error as badly and _then_ fix Takahē to accept a string there.
