### ISSUE TITLE
Show replies below posts on the individual-post page

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#59]
They're already in the DB, just need pulling out and displaying with a slightly different style?

**Comment by rimu** [comment]
Have you considered the case where the replies are _not yet_ in the DB?

e.g. this long-standing problem that has bewildered many:
https://github.com/mastodon/mastodon/issues/9409
https://github.com/mastodon/mastodon/issues/21497
https://github.com/mastodon/mastodon/issues/21571
https://github.com/mastodon/mastodon/issues/22674 

If you can/have solve(d) this I'll switch to any takahe instance straight away!

**Comment by andrewgodwin** [comment]
So we're planning to solve this for the _ancestors_, since those we can reliably fetch in the background, but there's no easy way of solving this for the _descendants_ as I don't believe there's a default activitypub way of getting replies for a post. That said, I hope we can eventually solve this at least for Takahē and Mastodon remote servers by using either an ordered collection or an API endpoint.
