### ISSUE TITLE
Clicking on a post should open its individual post page

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#60]
Probably have to do this using JavaScript as I'm not sure we can wrap an `<a>` around the whole thing sensibly.

**Comment by TkTech** [comment]
See https://getbootstrap.com/docs/4.3/utilities/stretched-link/ for the simple trick bootstrap uses.

**Comment by andrewgodwin** [comment]
I think the problem with that technique is that it would override any links in the text as it sits on top. It's possible something similar with a negative z-index might work if we can get the stacking order right.
