### ISSUE TITLE
Bulk Approve Hashtags

### ISSUE THREAD

**Issue by doodlemania2** [jointakahe/takahe#614]
I'd like ability to bulk approve hashtags (or auto approve) and then go back and hide those that are objectionable. Maybe a direct DB workaround?

**Comment by andrewgodwin** [comment]
To be clear, you want to keep the "Unreviewed hashtags are public" feature _off_, but bulk approve and then remove a couple later on? There's certainly SQL I can give you to do that, but it might be easier to make the Django Admin have that as an action as it has a better bulk edit interface.

**Comment by andrewgodwin** [comment]
Well that's what this toggle is:

![image](https://github.com/jointakahe/takahe/assets/36182/9a0d2fa5-a55a-4f41-9716-a95d9dcc2b16)

(admin -> basic)

**Comment by doodlemania2** [comment]
Ooooof. Sorry sir 🤦‍♂️
