### ISSUE TITLE
Handle federated followers-only posts, currently treated same as mentioned-only

### ISSUE THREAD

**Issue by futzle** [jointakahe/takahe#616]
Posted a toot on Mastodon 4.0.x (Hometown, technically) with "Followers" visibility. No users were mentioned in it:
<img width="341" alt="image" src="https://github.com/jointakahe/takahe/assets/10947921/680e2ffa-577d-4116-8d98-4af4a503036f">

It appears in the Takahē database with Visibility = Mentioned (i.e., a "DM").
<img width="828" alt="image" src="https://github.com/jointakahe/takahe/assets/10947921/577b03df-7afe-4760-b811-3ab629b9ae26">
(And it does not appear in the timeline of a user who follows the author, because they weren't mentioned.)

Expected: the post appears in the database with Visibility = Followers.

Takahē 0.9.0 Docker image.

**Comment by futzle** [comment]
Visibility remains Mentioned after the state changes to fanned_out.

For more fun, if the original poster on Mastodon boosts their followers-only post, it _does_ appear in the Takahē user's timeline, with the client's DM bubble around it:
![IMG_1908](https://github.com/jointakahe/takahe/assets/10947921/541833c4-1377-4cb9-8aa1-4e4a147d054c)

**Comment by futzle** [comment]
I tested all the post types that federate: public (works), unlisted (works), mentioned-only (works). Only followers-only posts get miscategorized as "Mentioned". And, reading the code, I cannot figure out why!

**Comment by andrewgodwin** [comment]
Oh right, I almost forgot I had put this shortcut in a while back - I wasn't seeing a lot of followers-only posts back then so I just decided to make it default to the even more restricted one.

Let me see if I can get a few test messages from my own server and get this working. We still don't fetch follower objects but we can now serve them, at least.

**Comment by andrewgodwin** [comment]
Alright, fix is into `main` to make it work both ways - the only thing I noticed is that Mastodon may not respect it as a followers-only post until it refreshes the identity to see that it has followers/following URIs. If you need to force that, just make a tiny edit to your profile and Takahē will ping all follower servers to make them pull it again.
