### ISSUE TITLE
Connection to database issues after upgrading to 0.10

### ISSUE THREAD

**Issue by tobru** [jointakahe/takahe#653]
After upgrading to 0.10.0 I have issues with too many connections to the database:

```
connection failed: remaining connection slots are reserved for non-replication superuser connections
```

With 0.9 that wasn't an issue.

How can I help to debug that one?

**Comment by tobru** [comment]
Downgrading to 0.9 is hard, because some backwards-incompatible schema changes. When starting 0.9:

```
django.db.utils.ProgrammingError: column users_domain.state_ready does not exist
LINE 1: SELECT "users_domain"."state_ready", "users_domain"."state_c...
```

**Comment by tobru** [comment]
OK, by tuning `TAKAHE_STATOR_CONCURRENCY` and `TAKAHE_STATOR_CONCURRENCY_PER_MODEL` I could get around it. The DB only allows 25 concurrent connections. That might have been enough in the past, but now it seems it needs more.

I'm closing this issue, it's not a bug.

**Comment by andrewgodwin** [comment]
Yeah, the new Stator is _considerably_ more efficient at connecting to the DB in parallel than before, so it'll use more connections unless you turn it down (I dropped the defaults already, but probably not enough for everyone)
