### ISSUE TITLE
Add caching proxy for profile/post images

### ISSUE THREAD

**Issue by andrewgodwin** [jointakahe/takahe#67]
Rather than prefetch, we're going to have a caching proxy for this instead. Easier to admin, slightly less load on target servers.

**Comment by manfre** [comment]
There should be a "Needs more JPEG" setting to aggressively downsample or a settable threshold where we let the host server deal with images that are too bloated to justify processing or caching.

**Comment by crdnl** [comment]
Mastodon has a timeout feature that keeps the retrieved images/content for `x` days.

**Comment by kromonos** [comment]
Another option would be making usage of proxing software like [morty](https://github.com/asciimoo/morty), like searx is doing.

**Comment by andrewgodwin** [comment]
I think our general approach might be, for remote images at least and maybe for profile pics, to just use a proxy model - build it into Takahē by default, but have it separable enough it can be pointed and run elsewhere.
