### ISSUE TITLE
statuses: `status` field not optional when `media_ids[]` present

### ISSUE THREAD

**Issue by ishigoya** [jointakahe/takahe#672]
I encountered this issue while creating a request with curl.

In the [Mastodon API](https://docs.joinmastodon.org/methods/statuses/#form-data-parameters),  the `status` field is optional when `media_ids[]` is present, however even in this case it appears to be required in Takahe.

Against mastodon.social (results in a successful post):

```console
$ curl -H "Authorization: Bearer <snip>" \
    -X POST -H "Content-Type: multipart/form-data" \
    https://mastodon.social/api/v1/media \ 
    --form file="@map.png" | jq
```

```console
$ curl -k -X POST     \
     -H "Authorization: Bearer <snip>"   \
    -F 'media_ids[]=<from above>'  \
    https://mastodon.social/api/v1/statuses
```

A similar request against a Takahe instance returns the following error:

```json
{
  "error": "invalid_input",
  "error_details": [
    {
      "loc": [
        "details",
        "status"
      ],
      "msg": "field required",
      "type": "value_error.missing"
    }
  ]
}
```

**Comment by andrewgodwin** [comment]
Yup, I guess that makes sense. This will be a good first bug for someone to fix.
