### ISSUE TITLE
Strip EXIF/metadata from all attachments/uploads

### ISSUE THREAD

**Issue by tabletcorry** [jointakahe/takahe#75]
Standard practice for social media (and other platforms like Slack) is to strip all metadata (EXIF and the like) from uploaded files, in order to protect users that don't know it is there. At the very least this would be the GPS data in most images, but might as well ditch everything.

Perhaps a new `strip_metadata` function can be created at called from various upload points such as https://github.com/jointakahe/takahe/blob/291d7e404e12e1d017403242f8ed199046f0904c/activities/models/post_attachment.py#L21-L20

**Comment by janaurka** [comment]
To do that properly, probably it requires a tool like [`mat2`](https://0xacab.org/jvoisin/mat2) which comes with some dependencies...

**Comment by andrewgodwin** [comment]
We're likely going to resize every single image that comes in anyway, as it turns out Mastodon can't handle images more than about 2000x2000 (it shrinks things down), so that process should be a good place to zero out all EXIF data, if it's not done already by resizing.

**Comment by tabletcorry** [comment]
If we are taking the processing hit of resizing, should it convert everything to webp or the like? Maybe as a Takahē config option? Could save a lot of server bandwidth.

**Comment by andrewgodwin** [comment]
Yeah, we discussed this in Discord during the week - webp for images seems like it would be pretty universally supported (once we check a few mobile clients), and once we go to video, we can maybe try webm/vp8 (vp9 has iOS support issues).

**Comment by andrewgodwin** [comment]
Takahē now resizes and reformats all uploaded images to webp, which seems to erase all EXIF data as a side effect, so this is done!
