### ISSUE TITLE
local:// MEDIA_BACKEND isn't supported

### ISSUE THREAD

**Issue by llimllib** [jointakahe/takahe#77]
The deployment docs say:

```
TAKAHE_MEDIA_BACKEND must be a URI starting with local://, s3:// or gcs://.

    If it is set to local://, you must also provide TAKAHE_MEDIA_ROOT, the path to the local media directory, and TAKAHE_MEDIA_URL, a fully-qualified URL prefix that serves that directory.
```
but if you actually try to use it, you hit [this line](https://github.com/jointakahe/takahe/blob/a3bc7ff196e09a1e995b47f53b05717282f0ba72/takahe/settings.py#L314) which raises `Unsupported media backend local`

**Comment by llimllib** [comment]
I suspect the right answer is just to remove that option from the docs?

**Comment by andrewgodwin** [comment]
Yup, I am still catching up with the settings changes - I'll go fix that now.
