### ISSUE TITLE
Experience report: deploying to Render

### ISSUE THREAD

**Issue by aviflax** [jointakahe/takahe#80]
Hi, I’m working on deploying Takahē to [Render](https://render.com). I ran into some snags and dead ends and I thought it might possibly help others, doing something similar, or maybe help inform improvements to the docs, for me to share the notes I took as I worked through it.

Some context that might be relevant:

* I’ve been a Web developer for 20+ years
* I’ve used Django here and there over the years but I’ve never been fully proficient with it, and at this point I’m rusty
* I’m hoping to use Takahē for my own personal microblogging and that’s it; this will be a single-user instance that I don’t think will ever have any notable traffic or load
* I’d like to use Render’s free plan for the Web service (i.e. the Web server)

## My ongoing notes

* I’m deploying from tip of `main` over 27–29 November 2022
* In order to run the initial migrations, the docs said I needed to run `manage.py migrate` somehow. So I used the Render settings to override the default command (`CMD`) of the container image to `manage.py migrate` But this didn’t work. And I didn’t get a useful error message. Eventually after staring at the `Dockerfile` I realized that I should probably make the command `python3 manage.py migrate` — and that worked
* The 512MB of RAM on the free plan wasn’t enough for the default configuration — my Gunicorn workers were terminated due to signal 9` which via [this SA answer](https://stackoverflow.com/a/67719886/7012) I learned was probably an out of memory condition
* I upgraded to a 1GB, $14/month plan, and the `signal 9` errors stopped, but the workers still didn’t quite “come up” — no problems were visible in the logs, but requests to the server got no response, even though the logs included “listening on …”
* Then I tried overriding the default number of workers (8) by setting the environment variable `GUNICORN_CMD_ARGS` to `--workers 2` — and that did it. The app came up and started serving requests.
* I’m not getting emails from the server, e.g. the initial user creation email.
	* I’m using Fastmail; I created an “app password” for the service, and Fastmail’s admin app shows that the app password has not yet been used. So I guess I must have an error in `TAKAHE_EMAIL_SERVER` but I don’t know what it is yet, and nothing is showing up in the logs, i.e. no error messages
	* I tried changing the query param `?tls=true` to `?ssl=true` but that didn’t seem to help
	* Ah, wait, I just noticed this: “Yes, because [password reset emails] are sent from background workers rather than a view.” from #55
		* That is clearly part of the problem — I haven’t set up the background workers yet.
		* I opened the Render “shell” feature and tried to run `python manage.py runstator` but I got an error: `django.db.utils.ProgrammingError: relation "activities_hashtag" does not exist`
		* uh, I guess I need to run migrations again? Does Django not automatically run those as-needed on startup? I guess not. I ran `python3 manage.py migrate` and it successfully ran a migration, then `runstator` seemed to work — and finally I got the email (3 actually)
	* I suspect there was never anything wrong with the email setup; but rather I’d made an erroneous assumption that emails were sent directly from the Web server rather than from a background task.
* Now I’m on the _Create New Identity_ page
	* I need to enter a username, fine, and select a _Domain_ — but I can’t because the dropdown is empty
	* Aha, I found the section [Adding A Domain](https://docs.jointakahe.org/en/latest/installation/#adding-a-domain) in the installation docs — that explains it
	* Created a domain, created an identity, looking good.
* The Web app seems to be up and running, and I had no trouble setting up the Stator Background Worker, which seems to be up and running as well
* I uploaded a profile icon to my identity, which succeeded, but the icon isn’t showing up in the app UI
	* I guess there must be something wrong with the way I’ve set up the bucket?
	* For example, with this URL: `https://s3.us-east-2.amazonaws.com/net.flaximus.takahe/profile_images/2022/11/29/TB5GVTAFP5EQVNMOGJLDVW5TQ4.jpeg?AWSAccessKeyId=REDACTED&Signature=1jXzRaVnVJuURa5ON6HVyXjKxm4%3D&Expires=1669771156` I get a 400 response with an XML error document with this message: `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`
	* I eventually determined that these URLs are generated by [django-storages](https://github.com/jschneier/django-storages) but that’s as far as I can get.
	* Some of the issues in this repo mention this problem but I can’t figure out how to apply the discussed solutions to my situation, wherein I’m running Takahe from an image built from the Dockerfile in the repo, so I don’t have an easy way to modify the `settings.py` file
	* It looks like maybe I need to set AWS_S3_SIGNATURE_VERSION to `s3v4`? But I wonder why this isn’t the default already in Takahē?
* I was able to downgrade the Render plan for my Web service back down to the free plan, and it seems to work fine now

----

HTH!

**Comment by aviflax** [comment]
Anyone have any tips/ideas for addressing my S3 image URL problem? Or maybe I should open a separate, more focused issue for that?

**Comment by andrewgodwin** [comment]
Thanks for the writeup - a few of these are definitely cases of our install docs needing work!

As for the S3 URLs, I've just pushed what I think is the appropriate settings fix for this - disabling signed URLs and setting all objects to public-read. You'll need to make sure your bucket allows this, and then go manually fix the ACL on any already-uploaded file (or just reupload them)

**Comment by aviflax** [comment]
My pleasure, and that’s great, thank you! I will update and give it a try and report back.

**Comment by aviflax** [comment]
Problem solved! Thanks!

**Comment by andrewgodwin** [comment]
Lovely! I'll close this then, as "improve the installation docs" is on my general list already, and I think that's mostly where your other feedback can pipe into.
