### ISSUE TITLE
Serverless mode vs responsiveness

### ISSUE THREAD

**Issue by belkadan** [jointakahe/takahe#90]
I'm interested in the (possible? partial? eventual?) goal of running Takahē in a serverless style, using either polling as described in the Installation instructions, or something more complicated in the future (maybe web hooks to schedule/reschedule work?). Of course, the drawback is that some actions don't happen synchronously:

> You have to run at least one Stator worker to make things like follows, posting, and timelines work.

> I was relying on my background task system a bit too much, and it meant that your own posts wouldn't even show up in your timeline until up to a minute later.

My *impression* is that this could be controlled by having the option to run certain tasks as background tasks *or* as foreground tasks. For example, in "serverless mode", posting could synchronously update the account's personal timeline, but delay the update to all other timelines; it could synchronously send replies in a conversation, but delay the send to your other followers.

Is this an interesting use case / setup mode at all?

**Comment by andrewgodwin** [comment]
This is actually how I had takahe.social working for a while; I've fixed most of the "responsiveness" issues (like seeing your own posts in your timeline) with a few exceptions where that code runs correctly.

As such, you can totally run things today with only regular polling of the Stator URL to trigger a brief worker flurry. We're not going to go more integrated than that, as there are things (like sending email or doing fetches from a remote server) that totally _do_ need some level of not-in-the-request worker, but provided you've got no more than a few tens of followers the model as we have it should work.
